
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[399] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
       89,   89,   95,   93,    1,    1,   92,   93,   92,   93,
       93,   94,   14,   94,   94,   94,   18,   94,   78,   94,
       94,   24,   94,   94,   94,   89,   89,   89,   89,   94,
       89,   94,    1,    1,   92,    0,   92,    0,    1,   92,
       92,   92,    0,    0,    0,   10,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   92,
        0,    0,    0,    0,    0,   23,    0,    0,    0,   89,
       89,   89,   89,   89,    0,   89,    0,    0,    1,   92,
        0,   92,    0,   92,   92,   91,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,   60,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       62,    0,    0,    0,   36,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   90,   88,   15,   61,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   63,    0,    0,   37,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   59,    0,    0,
        0,    0,   35,    0,    0,   56,    0,   54,   52,   64,

        0,    0,   38,   40,   42,   44,    0,    0,   19,   48,
       50,    0,    0,    0,    0,    0,   86,   82,    0,   84,
       66,   46,    0,    0,    0,    0,    0,    0,    0,    0,
       88,    0,    0,    0,   57,    0,   55,   53,   65,    0,
        0,   39,   41,   43,   45,    0,    0,   49,   51,    0,
        0,    0,    0,    0,   87,   83,    0,   85,   67,   47,
        0,   34,    0,    0,   32,    0,    0,   16,    0,    0,
       19,    0,    0,   72,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   33,    0,
        0,    0,    0,    0,    0,    0,   73,   75,    0,    0,

        6,    0,    0,    0,    0,   16,    4,    2,    0,    0,
       76,    0,    0,    0,    0,    0,    0,    0,    0,   20,
        0,    7,    0,    0,    0,    0,   29,    5,    3,    0,
        0,    0,    0,    0,    0,    0,    0,   70,    0,   76,
        8,    0,   11,    0,   13,    0,    0,   17,    0,    0,
       20,    0,    0,    0,    0,    0,   71,    0,   79,    9,
        0,   30,    0,   25,   68,   11,   13,    0,   12,   17,
        0,    0,    0,   21,    0,   31,    0,   26,   69,   80,
        0,   12,    0,   77,    0,   22,   21,   81,    0,    0,
       77,   22,    0,    0,    0,   27,   28,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,    1,
        1,    1,    1,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   15,   15,   15,   15,   15,   20,   21,   22,
       23,   24,   25,    1,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   35,   36,   37,   38,   39,   40,
       35,   41,   42,   43,   44,   45,   46,   35,   47,   48,
        1,   49,    1,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   35,   35,   60,   61,   62,
       63,   64,   35,   65,   66,   67,   68,   69,   70,   35,
       71,   72,    7,   73,    7,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[74] =
    {   0,
        1,    2,    2,    3,    2,    4,    2,    1,    2,    4,
        2,    1,    4,    4,    4,    4,    4,    4,    4,    4,
        2,    5,    6,    5,    2,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    7,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    8
    } ;

static yyconst flex_uint16_t yy_base[414] =
    {   0,
        0,   73,    2,    3,    5,    6,    4,   10,   54,   75,
      146,  219,  969,  997,  107,    3,  159,  961,  172,  288,
      955,  997,  997,    1,    6,    4,  997,   20,  997,    4,
      935,  997,    3,   18,   21,  188,  235,  201,  246,  945,
      262,  943,  274,  286,  355,  943,  358,  930,   11,  368,
      383,  387,   82,  897,  387,  903,   66,   89,  423,   64,
      114,  418,   67,   54,   66,  882,  237,  465,   70,  461,
       84,   99,  100,  116,  124,  997,  121,  150,  156,  490,
      515,  528,  539,  552,  896,  563,  891,  877,  576,  588,
      896,  591,  891,  601,  616,  997,  886,  873,  240,  207,

      588,  247,  286,  616,  872,  156,  250,  871,  600,  658,
      276,  890,  997,  180,  465,  269,  275,  869,  281,  868,
      867,  862,  186,  291,  861,  860,  859,  858,  202,  336,
      997,  204,  857,  856,  997,  312,  335,  392,  347,  855,
      854,  338,  853,  851,  997,  849,  353,  394,  346,  403,
      433,  448,  848,  358,  997,  865,  997,  997,  455,  364,
      440,  843,  443,  840,  839,  838,  460,  475,  837,  835,
      834,  832,  471,  490,  997,  831,  830,  997,  478,  495,
      588,  519,  827,  825,  500,  812,  776,  997,  741,  535,
      661,  731,  997,  571,  586,  997,  724,  997,  997,  997,

      626,  602,  997,  997,  997,  997,  527,  613,  703,  997,
      997,  614,  617,  653,  636,  621,  997,  997,  622,  997,
      997,  997,  616,  607,  531,  584,  554,  565,  132,  618,
      585,  615,  623,  629,  997,  546,  997,  997,  997,  660,
      635,  997,  997,  997,  997,  660,  659,  997,  997,  661,
      659,  530,  523,  664,  997,  997,  667,  997,  997,  997,
      490,  997,  659,  675,  997,  680,  667,  507,  483,  452,
      471,  674,  673,  997,  997,  685,  690,  723,  731,  451,
      732,  685,  693,  733,  448,  436,  710,  716,  997,  721,
      708,  398,  387,  386,  715,  714,  997,  997,  723,  724,

      997,  717,  716,  718,  729,  398,  997,  997,  371,  729,
      364,  341,  756,  757,  758,  764,  312,  311,  777,  319,
      779,  997,  738,  747,  750,  761,  997,  997,  997,  283,
      760,  277,  272,  756,  267,  752,  246,  997,  239,  250,
      997,  787,  246,  792,  231,  793,  801,  219,  803,  814,
      213,  815,  770,  192,  767,  178,  997,  176,  997,  997,
      171,  997,  781,  997,  997,  183,  182,  816,  178,  168,
      817,  829,  832,  146,  113,  997,  794,  997,  997,  997,
      794,  131,  835,  130,  837,   88,   49,  997,  805,  808,
       48,   47,  810,   20,   15,  997,  997,  997,  910,  918,

      926,  933,    7,  938,  942,  946,  952,  958,  964,  970,
      976,  982,  988
    } ;

static yyconst flex_int16_t yy_def[414] =
    {   0,
      399,  399,  400,  400,  400,  400,  400,  400,  400,  400,
      401,  401,  398,  398,  402,  398,  402,  403,  402,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  404,  404,  404,  404,  398,
      404,  398,  402,  405,  402,  398,  402,  398,  398,  402,
      405,  402,  403,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  402,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  404,
      404,  404,  404,  404,  398,  404,  398,  398,  405,  405,
      398,  405,  398,  402,  405,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  406,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  407,  408,  398,  409,  398,  398,  406,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  407,  398,  408,  398,  410,  409,  398,  398,  398,
      398,  411,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  410,  398,  398,
      412,  413,  411,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  412,  398,  413,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,    0,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398
    } ;

static yyconst flex_uint16_t yy_nxt[1071] =
    {   0,
       14,   15,   16,   15,   49,   49,   49,   14,   18,   53,
       19,   14,   49,   49,   49,  398,  398,  398,  398,   19,
      398,   20,  398,   14,   21,   23,   23,   29,   27,   27,
       30,   72,   77,   29,   24,   24,   30,   73,  397,   25,
       25,   71,   75,  396,   26,   26,   28,   28,   14,   14,
      392,  391,  387,   74,   79,   30,   72,   77,   78,   24,
       24,   30,   73,   25,   25,   71,   75,   31,   26,   26,
       28,   28,   14,   14,   15,   16,   15,   32,   74,   79,
       14,   18,   78,   19,   14,  398,   33,  133,   31,  113,
      131,  392,   19,  145,   20,   34,   14,   21,   32,   35,

      122,  134,   96,  132,  114,  146,  115,   33,   43,   44,
       43,   33,  133,  147,  116,   46,   34,   47,  117,   34,
       35,   14,   14,   35,  122,  134,   47,  132,  114,  146,
      115,   48,   33,  391,  382,  148,  388,  284,  147,  116,
       34,  284,  149,  117,   35,   14,   22,  123,   37,  387,
       38,   38,  124,   22,  152,   38,   39,   40,   41,  148,
       50,   51,   50,  150,  151,   41,  149,   46,   22,   47,
       42,  370,  123,   50,   51,   50,  124,  153,   47,  152,
       46,  382,   47,   48,  154,  367,  366,  150,  151,  176,
       81,   47,   82,   82,  380,   22,   48,   82,   83,  379,

       84,  378,  153,   81,  284,   82,   82,   84,  190,  154,
       82,   83,   85,   84,  176,  376,  351,  201,   22,   22,
       84,   37,  370,   38,   38,   85,   22,  207,   38,   39,
       40,   41,  160,  190,  367,  209,  161,   86,   41,   82,
       82,   22,  201,   42,   82,   83,   87,   84,   81,  366,
       82,   82,  207,  340,   84,   82,   83,  160,   84,   85,
      209,  161,  365,  158,   81,   84,   82,   82,   22,  364,
       85,   82,   83,  136,   84,   43,   44,   43,  159,  137,
      138,   84,   46,  166,   47,  177,   85,   89,   44,   89,
      362,   22,   54,   47,   91,  360,   92,  136,   48,  188,

      359,   55,  159,  137,  138,   92,  357,  166,  194,  177,
       93,  189,  195,   56,   57,   58,   59,   60,   61,  167,
       62,   63,  351,   64,  168,  197,   65,   66,  202,   67,
       68,   69,  194,  350,  349,  189,  195,  212,   56,   57,
       58,   59,   60,   61,  167,   62,   63,   64,  168,  197,
       65,   66,  202,   67,   68,   69,   50,   51,   50,   50,
       51,   50,  212,   46,  341,   47,   46,  340,   47,   50,
       51,   50,  208,  216,   47,  213,   46,   47,   47,   48,
      219,  225,   48,  223,   95,   51,   95,   47,   50,   51,
       50,   91,   48,   92,  338,   46,  208,   47,  216,  213,

      230,  306,   92,  233,  219,  225,   47,   93,  223,  329,
      328,   48,   98,   99,  100,  101,  102,  103,  214,  104,
      105,  327,  106,  224,  230,  107,  108,  233,  109,  110,
      111,  215,  226,  125,  126,  127,  128,   98,   99,  100,
      101,  102,  103,  214,  104,  105,  106,  129,  224,  107,
      108,  118,  109,  110,  111,  215,  119,  226,  120,  322,
      130,  227,   50,   51,   50,  121,  191,  191,  191,   46,
      321,   47,  129,  315,  271,  308,  118,  234,  192,  228,
       47,  119,  120,  232,  130,   48,  227,  236,  193,  121,
      139,  240,   81,  140,   82,   82,  246,  141,  142,   82,

       83,  234,   84,  250,  228,  143,  307,  144,  232,   84,
      306,  236,  241,  301,   85,  139,  240,   81,  140,   82,
       82,  246,  141,  142,   82,   83,  247,   84,  250,  143,
       81,  144,   82,   82,   84,  251,  241,   82,   83,   85,
       84,   81,  257,   82,   82,  254,  298,   84,   82,   83,
      247,   84,   85,  297,   81,  269,   82,   82,   84,  251,
      280,   82,   83,   85,   84,   86,  257,   82,   82,  289,
      254,   84,   82,   83,   87,   84,   85,   89,   44,   89,
      269,  261,   84,  282,   91,  280,   92,   85,  231,   95,
       51,   95,   95,   51,   95,   92,   91,  283,   92,   91,

       93,   92,   50,   51,   50,  261,  281,   92,  282,   46,
       92,   47,   93,  263,  252,   93,  162,   95,   51,   95,
       47,  163,  283,  164,   91,   48,   92,  253,  264,  279,
      165,  169,  170,  171,  172,   92,  179,  263,  278,  252,
       93,  162,  180,  181,  268,  173,  163,  164,  270,  272,
      285,  253,  264,  266,  165,  273,  276,  277,  174,  275,
      179,  286,  191,  191,  191,  287,  180,  181,  268,  267,
      173,  288,  270,  272,  192,  285,  274,  292,  266,  273,
      276,  277,  174,  182,  193,  286,  183,  290,  293,  287,
      184,  185,  302,  267,  294,  288,  295,  296,  186,  299,

      187,  292,  300,  291,  303,  304,  271,  305,  182,  309,
      310,  183,  290,  293,  311,  184,  185,  302,  294,  312,
      295,  296,  186,  299,  187,  317,  300,  291,  313,  303,
      304,  305,  313,  309,  310,  318,  314,  316,  320,  311,
      314,  316,  320,  323,  312,  324,  325,  265,  326,  317,
      330,  331,  332,  333,  262,  334,  335,  336,  337,  318,
      339,  343,  345,  346,  260,  343,  345,  346,  323,  348,
      324,  325,  326,  348,  330,  331,  353,  332,  333,  334,
      335,  336,  320,  337,  352,  339,  320,  354,  352,  355,
      356,  358,  343,  361,  363,  313,  343,  345,  369,  259,

      353,  345,  369,  314,  316,  320,  348,  375,  371,  377,
      348,  354,  371,  355,  381,  356,  358,  361,  363,  372,
      374,  369,  384,  372,  374,  369,  384,  389,  343,  345,
      346,  375,  390,  377,  386,  258,  348,  374,  386,  381,
      384,  374,  386,  393,  384,  394,  386,  395,  256,  320,
      255,  352,  389,  249,  248,  245,  390,  244,  243,  343,
      242,  239,  238,  237,  345,  369,  235,  393,  231,  394,
      229,  395,  222,  348,  221,  371,  220,  218,  217,  211,
      210,  206,  205,  204,  203,  200,  372,  374,  369,  384,
      199,  198,  196,  112,  178,  175,  157,  156,   90,   51,

      155,  386,   88,   82,  374,  135,  112,  384,   97,  386,
       17,   17,   17,   17,   17,   17,   17,   17,   22,   22,
       22,   22,   22,   22,   22,   22,   36,   36,   36,   36,
       36,   36,   36,   36,   45,   45,   45,   45,   45,   80,
       80,   80,   80,   90,   90,   90,   94,   90,  319,  319,
       82,  319,  319,  319,  342,  342,   88,  342,   76,  342,
      344,  344,   70,  344,   52,  344,  347,  347,  398,  347,
      398,  347,  368,  368,  398,  368,  398,  368,  373,  373,
      398,  373,  398,  373,  383,  383,  398,  383,  398,  383,
      385,  385,  398,  385,  398,  385,   13,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398
    } ;

static yyconst flex_int16_t yy_chk[1071] =
    {   0,
        1,    1,    1,    1,   16,   16,   16,    1,    1,  403,
        1,    1,   49,   49,   49,    0,    0,    0,    0,    1,
        0,    1,    0,    1,    1,    3,    4,    7,    5,    6,
        7,   25,   33,    8,    3,    4,    8,   26,  395,    3,
        4,   24,   30,  394,    3,    4,    5,    6,    1,    1,
      392,  391,  387,   28,   35,    7,   25,   33,   34,    3,
        4,    8,   26,    3,    4,   24,   30,    9,    3,    4,
        5,    6,    1,    2,    2,    2,    2,    9,   28,   35,
        2,    2,   34,    2,    2,   53,    9,   64,   10,   57,
       63,  386,    2,   69,    2,    9,    2,    2,   10,    9,

       60,   65,   53,   63,   57,   69,   57,   10,   15,   15,
       15,    9,   64,   71,   58,   15,   10,   15,   58,    9,
       10,    2,    2,    9,   60,   65,   15,   63,   57,   69,
       57,   15,   10,  384,  382,   72,  375,  229,   71,   58,
       10,  229,   73,   58,   10,    2,   11,   61,   11,  374,
       11,   11,   61,   11,   77,   11,   11,   11,   11,   72,
       17,   17,   17,   74,   75,   11,   73,   17,   11,   17,
       11,  370,   61,   19,   19,   19,   61,   78,   17,   77,
       19,  369,   19,   17,   79,  367,  366,   74,   75,  106,
       36,   19,   36,   36,  361,   11,   19,   36,   36,  358,

       36,  356,   78,   38,  229,   38,   38,   36,  114,   79,
       38,   38,   36,   38,  106,  354,  351,  123,   11,   12,
       38,   12,  348,   12,   12,   38,   12,  129,   12,   12,
       12,   12,  100,  114,  345,  132,  100,   37,   12,   37,
       37,   12,  123,   12,   37,   37,   37,   37,   39,  343,
       39,   39,  129,  340,   37,   39,   39,  100,   39,   37,
      132,  100,  339,   99,   41,   39,   41,   41,   12,  337,
       39,   41,   41,   67,   41,   43,   43,   43,   99,   67,
       67,   41,   43,  102,   43,  107,   41,   44,   44,   44,
      335,   12,   20,   43,   44,  333,   44,   67,   43,  111,

      332,   20,   99,   67,   67,   44,  330,  102,  116,  107,
       44,  111,  117,   20,   20,   20,   20,   20,   20,  103,
       20,   20,  320,   20,  103,  119,   20,   20,  124,   20,
       20,   20,  116,  318,  317,  111,  117,  136,   20,   20,
       20,   20,   20,   20,  103,   20,   20,   20,  103,  119,
       20,   20,  124,   20,   20,   20,   45,   45,   45,   47,
       47,   47,  136,   45,  312,   45,   47,  311,   47,   50,
       50,   50,  130,  139,   45,  137,   50,   47,   50,   45,
      142,  149,   47,  147,   51,   51,   51,   50,   52,   52,
       52,   51,   50,   51,  309,   52,  130,   52,  139,  137,

      154,  306,   51,  160,  142,  149,   52,   51,  147,  294,
      293,   52,   55,   55,   55,   55,   55,   55,  138,   55,
       55,  292,   55,  148,  154,   55,   55,  160,   55,   55,
       55,  138,  150,   62,   62,   62,   62,   55,   55,   55,
       55,   55,   55,  138,   55,   55,   55,   62,  148,   55,
       55,   59,   55,   55,   55,  138,   59,  150,   59,  286,
       62,  151,   70,   70,   70,   59,  115,  115,  115,   70,
      285,   70,   62,  280,  271,  270,   59,  161,  115,  152,
       70,   59,   59,  159,   62,   70,  151,  163,  115,   59,
       68,  167,   80,   68,   80,   80,  173,   68,   68,   80,

       80,  161,   80,  179,  152,   68,  269,   68,  159,   80,
      268,  163,  168,  261,   80,   68,  167,   81,   68,   81,
       81,  173,   68,   68,   81,   81,  174,   81,  179,   68,
       82,   68,   82,   82,   81,  180,  168,   82,   82,   81,
       82,   83,  185,   83,   83,  182,  253,   82,   83,   83,
      174,   83,   82,  252,   84,  207,   84,   84,   83,  180,
      225,   84,   84,   83,   84,   86,  185,   86,   86,  236,
      182,   84,   86,   86,   86,   86,   84,   89,   89,   89,
      207,  190,   86,  227,   89,  225,   89,   86,  231,   90,
       90,   90,   92,   92,   92,   89,   90,  228,   90,   92,

       89,   92,   94,   94,   94,  190,  226,   90,  227,   94,
       92,   94,   90,  194,  181,   92,  101,   95,   95,   95,
       94,  101,  228,  101,   95,   94,   95,  181,  195,  224,
      101,  104,  104,  104,  104,   95,  109,  194,  223,  181,
       95,  101,  109,  109,  202,  104,  101,  101,  208,  212,
      230,  181,  195,  201,  101,  213,  216,  219,  104,  215,
      109,  232,  191,  191,  191,  233,  109,  109,  202,  201,
      104,  234,  208,  212,  191,  230,  214,  241,  201,  213,
      216,  219,  104,  110,  191,  232,  110,  240,  246,  233,
      110,  110,  263,  201,  247,  234,  250,  251,  110,  254,

      110,  241,  257,  240,  264,  266,  209,  267,  110,  272,
      273,  110,  240,  246,  276,  110,  110,  263,  247,  277,
      250,  251,  110,  254,  110,  282,  257,  240,  278,  264,
      266,  267,  278,  272,  273,  283,  279,  281,  284,  276,
      279,  281,  284,  287,  277,  288,  290,  197,  291,  282,
      295,  296,  299,  300,  192,  302,  303,  304,  305,  283,
      310,  313,  314,  315,  189,  313,  314,  315,  287,  316,
      288,  290,  291,  316,  295,  296,  323,  299,  300,  302,
      303,  304,  319,  305,  321,  310,  319,  324,  321,  325,
      326,  331,  342,  334,  336,  278,  342,  344,  346,  187,

      323,  344,  346,  279,  281,  284,  347,  353,  349,  355,
      347,  324,  349,  325,  363,  326,  331,  334,  336,  350,
      352,  368,  371,  350,  352,  368,  371,  377,  313,  314,
      315,  353,  381,  355,  372,  186,  316,  373,  372,  363,
      383,  373,  385,  389,  383,  390,  385,  393,  184,  319,
      183,  321,  377,  177,  176,  172,  381,  171,  170,  342,
      169,  166,  165,  164,  344,  346,  162,  389,  156,  390,
      153,  393,  146,  347,  144,  349,  143,  141,  140,  134,
      133,  128,  127,  126,  125,  122,  350,  352,  368,  371,
      121,  120,  118,  112,  108,  105,   98,   97,   93,   91,

       88,  372,   87,   85,  373,   66,   56,  383,   54,  385,
      399,  399,  399,  399,  399,  399,  399,  399,  400,  400,
      400,  400,  400,  400,  400,  400,  401,  401,  401,  401,
      401,  401,  401,  401,  402,  402,  402,   48,  402,  404,
      404,  404,  404,  405,  405,  405,   46,  405,  406,  406,
       42,  406,  406,  406,  407,  407,   40,  407,   31,  407,
      408,  408,   21,  408,   18,  408,  409,  409,   13,  409,
        0,  409,  410,  410,    0,  410,    0,  410,  411,  411,
        0,  411,    0,  411,  412,  412,    0,  412,    0,  412,
      413,  413,    0,  413,    0,  413,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main_lexer.l"
/* Declaration section*/
#line 4 "main_lexer.l"
#include<stdio.h>
#include<string.h>
#include"ast_grammar.tab.h"





#line 847 "lex.yy.c"

#define INITIAL 0
#define href 1
#define sizetag 2
#define table 3
#define src 4
#define comment 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 23 "main_lexer.l"

#line 1072 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 399 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 997 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 24 "main_lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "main_lexer.l"
{	
						//printf("HTML_S\n");
						return HTML_S;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "main_lexer.l"
{	
						//printf("HTML_E\n");
						return HTML_E;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "main_lexer.l"
{	
						//printf("HEAD_S\n");
						return HEAD_S;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "main_lexer.l"
{	
						//printf("HEAD_E\n");
						return HEAD_E;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 54 "main_lexer.l"
{	
						//printf("BODY_S\n");
						return BODY_S;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 60 "main_lexer.l"
{	
						//printf("BODY_E\n");
						return BODY_E;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "main_lexer.l"
{
						//printf("TITLE_S\n");
						return TITLE_S;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "main_lexer.l"
{
						//printf("TITLE_E\n");
						return TITLE_E;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "main_lexer.l"
{
						//printf("HREF_S\n");
						BEGIN href;
						return HREF_S;
					}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 86 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_LINK;
									}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 99 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_TITLE;
									}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_NAME;
									}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 124 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 132 "main_lexer.l"
{	
						//printf("HREF_E\n");
						return HREF_E;
					}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 138 "main_lexer.l"
{
						//printf("FONT_S\n\n");

						BEGIN sizetag;
						return FONT_S;
					}
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 147 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return FONT_SIZE;
									}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 159 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 165 "main_lexer.l"
{
						//printf("IMG Begin\n");
						BEGIN src;
						return IMG_S;
					}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 175 "main_lexer.l"
{
									//printf("SRC\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return IMG_SRC;
								}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 189 "main_lexer.l"
{
									//printf("WIDTH\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return IMG_WIDTH;
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 204 "main_lexer.l"
{
									//printf("HEIGHT\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);									
									return IMG_HEIGHT;
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 219 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 225 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 233 "main_lexer.l"
{
						//printf("FIG_S");
						return FIG_S;
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 238 "main_lexer.l"
{
						//printf("FIG_E");
						return FIG_E;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 243 "main_lexer.l"
{
						//printf("FIGCAP_S");
						return FIGCAP_S;
					}		
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 248 "main_lexer.l"
{
						//printf("FIGCAP_E");
						return FIGCAP_E;
					}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 253 "main_lexer.l"
{
						//printf("FONT_E\n\n");
						return FONT_E;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 259 "main_lexer.l"
{
						//printf("CENTER_S\n");
						return CENTER_S;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 265 "main_lexer.l"
{
						//printf("CENTER_E\n");
						return CENTER_E;
					}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 271 "main_lexer.l"
{
						//printf("DIV_S\n");
						return DIV_S;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 277 "main_lexer.l"
{
						//printf("DIV_E\n");
						return DIV_E;
					}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 285 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 290 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 295 "main_lexer.l"
{
						//printf("P_S\n");
						return P_S;
					}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 301 "main_lexer.l"
{
						//printf("P_E\n");
						return P_E;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 307 "main_lexer.l"
{
						//printf("H1_S\n");
						return H1_S;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 313 "main_lexer.l"
{
						//printf("H1_E\n");
						return H1_E;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 319 "main_lexer.l"
{
						//printf("H2_S\n");
						return H2_S;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 325 "main_lexer.l"
{
						//printf("H2_E\n");
						return H2_E;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 331 "main_lexer.l"
{
						//printf("H3_S\n");
						return H3_S;
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 336 "main_lexer.l"
{
						//printf("H3_E\n");
						return H3_E;
					}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 341 "main_lexer.l"
{
						//printf("H4_S\n");
						return H4_S;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 347 "main_lexer.l"
{
						//printf("H4_E\n");
						return H4_E;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 353 "main_lexer.l"
{
						//printf("UL_S\n");
						return UL_S;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 359 "main_lexer.l"
{
						//printf("UL_E\n");
						return UL_E;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 364 "main_lexer.l"
{
						//printf("LI_S\n");
						return LI_S;
					}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 370 "main_lexer.l"
{
						//printf("LI_E\n");
						return LI_E;
					}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 375 "main_lexer.l"
{
						//printf("OL_S\n");
						return OL_S;
					}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 381 "main_lexer.l"
{
						//printf("OL_E\n");
						return OL_E;
					}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 386 "main_lexer.l"
{
						//printf("DT_S\n");
						return DT_S;
					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 392 "main_lexer.l"
{
						//printf("DT_E\n");
						return DT_E;
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 397 "main_lexer.l"
{
						//printf("DL_S\n");
						return DL_S;
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 403 "main_lexer.l"
{
						//printf("DL_E\n");
						return DL_E;
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 408 "main_lexer.l"
{
						//printf("DD_S\n");
						return DD_S;
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 414 "main_lexer.l"
{
						//printf("DD_E\n");
						return DD_E;
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 420 "main_lexer.l"
{
						//printf("U_S\n");
						return U_S;
					}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 425 "main_lexer.l"
{
						//printf("U_E\n");
						return U_E;
					}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 430 "main_lexer.l"
{
						//printf("B_S\n");
						return B_S;
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 435 "main_lexer.l"
{
						//printf("B_E\n");
						return B_E;
					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 440 "main_lexer.l"
{
						//printf("I_S\n");
						return I_S;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 445 "main_lexer.l"
{
						//printf("I_E\n");
						return I_E;
					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 450 "main_lexer.l"
{
						//printf("EM_S\n");
						return EM_S;
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 455 "main_lexer.l"
{
						//printf("EM_E\n");
						return EM_E;
					}					
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 460 "main_lexer.l"
{
						//printf("TT_S\n");
						return TT_S;
					}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 465 "main_lexer.l"
{
						//printf("TT_E\n");
						return TT_E;
					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 471 "main_lexer.l"
{
						//printf("STRONG_S\n");
						return STRONG_S;
					}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 476 "main_lexer.l"
{
						//printf("STRONG_E\n");
						return STRONG_E;
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 482 "main_lexer.l"
{
						//printf("SMALL_S\n");
						return SMALL_S;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 487 "main_lexer.l"
{
						//printf("SMALL_E\n");
						return SMALL_E;
					}			
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 494 "main_lexer.l"
{
						//printf("SUB_S\n");
						return SUB_S;
					}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 500 "main_lexer.l"
{
						//printf("SUB_E\n");
						return SUB_E;
					}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 505 "main_lexer.l"
{
						//printf("SUP_S\n");
						return SUP_S;
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 511 "main_lexer.l"
{
						//printf("SUP_E\n");
						return SUP_E;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 516 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN table;
						return TABLE_S;
					}
	YY_BREAK

case 77:
YY_RULE_SETUP
#line 524 "main_lexer.l"
{
									//printf("BORDER i\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return TABLE_BORDER;
								}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 538 "main_lexer.l"
{
										BEGIN 0;
								}	
	YY_BREAK

case 79:
YY_RULE_SETUP
#line 546 "main_lexer.l"
{
						//printf("TABLE_E\n");
						return TABLE_E;
					}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 552 "main_lexer.l"
{
						//printf("CAPTION_S\n");
						return CAPTION_S;
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 558 "main_lexer.l"
{
						//printf("CAPTION_E\n");
						return CAPTION_E;
					}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 564 "main_lexer.l"
{
						//printf("TH_S\n");
						return TH_S;
					}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 570 "main_lexer.l"
{
						//printf("TH_E\n");
						return TH_E;
					}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 576 "main_lexer.l"
{
						//printf("TR_S\n");
						return TR_S;
					}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 582 "main_lexer.l"
{
						//printf("TR_E\n");
						return TR_E;
					}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 588 "main_lexer.l"
{
						//printf("TD_S\n");
						return TD_S;
					}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 594 "main_lexer.l"
{
						//printf("TD_E\n");
						return TD_E;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 600 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN comment;
						//return TABLE_S;
					}
	YY_BREAK

case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 608 "main_lexer.l"
{
										//printf("Comment %s Comment_end\n",yytext);
										yylval.s = (char *)malloc(100);	
										yylval.s = yytext;
										return COMMENT;
										
									}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 615 "main_lexer.l"
{
										BEGIN 0;
									}
	YY_BREAK

case 91:
YY_RULE_SETUP
#line 623 "main_lexer.l"
{	
						//printf("GreekL -%s\n",yytext);
						yylval.s = strdup(yytext);
						return GREEK;
					}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 629 "main_lexer.l"
{
						//printf("Contents -%s\n",yytext);
						yylval.s = strdup(yytext);
						return DATA;
					}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 641 "main_lexer.l"
;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 644 "main_lexer.l"
ECHO;
	YY_BREAK
#line 1967 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(href):
case YY_STATE_EOF(sizetag):
case YY_STATE_EOF(table):
case YY_STATE_EOF(src):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 399 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 399 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 398);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 644 "main_lexer.l"


  
int yywrap()
{
	return 1;	
} 
/*int main(int argc,char *argv[])
{
	yyin = fopen(argv[1],"r");
	//tex_file = fopen(argv[2],"w+");
	yylex();
}  */   


