
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 94
#define YY_END_OF_BUFFER 95
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[399] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
       89,   89,   95,   93,    1,    1,   92,   93,   92,   93,
       93,   94,   14,   94,   94,   94,   18,   94,   78,   94,
       94,   24,   94,   94,   94,   89,   89,   89,   89,   94,
       89,   94,    1,    1,   92,    0,   92,    0,    1,   92,
       92,   92,    0,    0,    0,   10,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   92,
        0,    0,    0,    0,    0,   23,    0,    0,    0,   89,
       89,   89,   89,   89,    0,   89,    0,    0,    1,   92,
        0,   92,    0,   92,   92,   91,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   10,   60,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       62,    0,    0,    0,   36,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   58,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   90,   88,   15,   61,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   63,    0,    0,   37,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   59,    0,    0,
        0,    0,   35,    0,    0,   56,    0,   54,   52,   64,

        0,    0,   38,   40,   42,   44,    0,    0,   19,   48,
       50,    0,    0,    0,    0,    0,   86,   82,    0,   84,
       66,   46,    0,    0,    0,    0,    0,    0,    0,    0,
       88,    0,    0,    0,   57,    0,   55,   53,   65,    0,
        0,   39,   41,   43,   45,    0,    0,   49,   51,    0,
        0,    0,    0,    0,   87,   83,    0,   85,   67,   47,
        0,   34,    0,    0,   32,    0,    0,   16,    0,    0,
       19,    0,    0,   72,   74,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   33,    0,
        0,    0,    0,    0,    0,    0,   73,   75,    0,    0,

        6,    0,    0,    0,    0,   16,    4,    2,    0,    0,
       76,    0,    0,    0,    0,    0,    0,    0,    0,   20,
        0,    7,    0,    0,    0,    0,   29,    5,    3,    0,
        0,    0,    0,    0,    0,    0,    0,   70,    0,   76,
        8,    0,   11,    0,   13,    0,    0,   17,    0,    0,
       20,    0,    0,    0,    0,    0,   71,    0,   79,    9,
        0,   30,    0,   25,   68,   11,   13,    0,   12,   17,
        0,    0,    0,   21,    0,   31,    0,   26,   69,   80,
        0,   12,    0,   77,    0,   22,   21,   81,    0,    0,
       77,   22,    0,    0,    0,   27,   28,    0

    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,    1,    1,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   16,   16,   16,   16,   16,   21,   22,   23,
       24,   25,   26,    8,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   37,   38,   39,   40,   41,
       36,   42,   43,   44,   45,   46,   47,   36,   48,   49,
        1,   50,    1,    8,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   36,   36,   61,   62,   63,
       64,   65,   36,   66,   67,   68,   69,   70,   71,   36,
       72,   73,    7,   74,    7,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[75] =
    {   0,
        1,    2,    2,    3,    2,    4,    2,    5,    5,    2,
        4,    2,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    2,    6,    7,    6,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    6,
        8,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    9
    } ;

static yyconst flex_uint16_t yy_base[414] =
    {   0,
        0,   74,    2,    3,    5,    6,    4,   10,   64,   67,
      148,  222,  915, 1027,  115,    3,  118,  910,  161,  292,
      904, 1027, 1027,    1,    6,    4, 1027,    9, 1027,   16,
      887, 1027,    3,   39,   25,  172,  189,  239,  256,  894,
      269,  897,  237,  282,  360,  901,  363,  895,   12,  375,
      388,  400,   18,  890,  400,  898,  212,   77,  378,   50,
      145,  431,   78,   33,   54,  876,  152,  473,  118,  468,
      111,   75,  102,  103,  146, 1027,  131,  152,  174,  471,
      490,  524,  537,  541,  891,  563,  886,  873,  569,  584,
      892,  596,  886,  599,  611, 1027,  880,  867,  192,  260,

      589,  151,  229,  610,  863,  244,  264,  861,  601,  652,
      273,  881, 1027,  258,  391,  265,  275,  859,  269,  856,
      855,  852,  284,  292,  850,  849,  848,  847,  291,  312,
     1027,  325,  845,  843, 1027,  353,  357,  445,  354,  842,
      841,  374,  833,  756, 1027,  749,  379,  432,  429,  450,
      454,  479,  716,  510, 1027,  728, 1027, 1027,  501,  518,
      522,  630,  534,  617,  572,  566,  524,  553,  545,  540,
      539,  535,  566,  569, 1027,  509,  501, 1027,  607,  570,
      607,  612,  499,  498,  594,  497,  496, 1027,  495,  595,
      649,  494, 1027,  603,  612, 1027,  493, 1027, 1027, 1027,

      639,  617, 1027, 1027, 1027, 1027,  628,  636,  510, 1027,
     1027,  638,  636,  488,  480,  640, 1027, 1027,  644, 1027,
     1027, 1027,  467,  455,  657,  434,  658,  656,  294,  657,
      443,  647,  654,  658, 1027,  400, 1027, 1027, 1027,  680,
      659, 1027, 1027, 1027, 1027,  662,  669, 1027, 1027,  684,
      683,  399,  395,  687, 1027, 1027,  691, 1027, 1027, 1027,
      394, 1027,  675,  698, 1027,  704,  691,  413,  372,  363,
      372,  699,  698, 1027, 1027,  707,  708,  735,  744,  347,
      747,  700,  699,  759,  345,  329,  709,  720, 1027,  732,
      720,  316,  315,  303,  731,  732, 1027, 1027,  741,  742,

     1027,  735,  735,  737,  748,  307, 1027, 1027,  284,  747,
      298,  274,  776,  777,  779,  783,  247,  242,  785,  253,
      797, 1027,  753,  758,  765,  776, 1027, 1027, 1027,  230,
      777,  213,  201,  773,  199,  769,  194, 1027,  193,  212,
     1027,  805,  207,  808,  204,  809,  816,  203,  817,  820,
      164,  823,  786,  133,  794,  125, 1027,  122, 1027, 1027,
      120, 1027,  804, 1027, 1027,  128,  105,  834,  102,   98,
      835,  836,  837,   92,   69, 1027,  809, 1027, 1027, 1027,
      812,   86,  849,   79,  850,   51,   50, 1027,  814,  824,
       49,   48,  826,   26,   20, 1027, 1027, 1027,  924,  933,

      942,  950,    5,  957,  962,  968,  975,  982,  989,  996,
     1003, 1010, 1017
    } ;

static yyconst flex_int16_t yy_def[414] =
    {   0,
      399,  399,  400,  400,  400,  400,  400,  400,  400,  400,
      401,  401,  398,  398,  402,  398,  402,  403,  402,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  404,  404,  404,  404,  398,
      404,  398,  402,  405,  402,  398,  402,  398,  398,  402,
      405,  402,  403,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  402,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  404,
      404,  404,  404,  404,  398,  404,  398,  398,  405,  405,
      398,  405,  398,  402,  405,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  406,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  407,  408,  398,  409,  398,  398,  406,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  407,  398,  408,  398,  410,  409,  398,  398,  398,
      398,  411,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  410,  398,  398,
      412,  413,  411,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  412,  398,  413,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,    0,  398,  398,

      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398
    } ;

static yyconst flex_uint16_t yy_nxt[1102] =
    {   0,
       14,   15,   16,   15,   49,   49,   49,   53,  398,   18,
      398,   19,   14,   49,   49,   49,  398,  398,  398,  398,
       19,  398,   20,  398,   14,   21,   23,   23,   29,   27,
       27,   30,   72,   77,   29,   24,   24,   30,   73,   96,
       25,   25,   71,   74,  397,   26,   26,   28,   28,   14,
      396,  392,  391,  387,  392,   75,   30,   72,   77,   79,
       24,   24,   30,   73,   25,   25,   71,  133,   74,   26,
       26,   28,   28,   14,   14,   15,   16,   15,   31,   75,
       78,   31,  391,   18,   79,   19,   14,  122,   32,  382,
      134,   32,  133,  388,   19,  387,   20,   33,   14,   21,

       33,  370,  131,  116,   78,  382,   34,  117,  367,   34,
       35,  122,  148,   35,  134,  132,   43,   44,   43,   50,
       51,   50,   33,   14,   46,   33,   47,   46,  116,   47,
       34,  366,  117,   34,   35,   47,  148,   35,   47,  132,
       48,  147,  145,   48,  380,  149,  379,   14,   22,  378,
       37,  150,   38,   38,  146,   22,   22,  376,   38,   39,
       40,   41,   50,   51,   50,  152,  147,  351,   41,  149,
       46,   22,   47,   42,   81,  150,   82,   82,  146,  123,
      153,   47,   82,   83,  124,   84,   48,  151,  166,  136,
      152,   86,   84,   82,   82,  137,  138,   85,   22,   82,

       83,   87,   84,  154,  123,  153,  370,  367,  124,   84,
      366,  151,  166,  136,   85,  340,  158,  365,  364,  137,
      138,   22,   22,  362,   37,  360,   38,   38,  154,   22,
       22,  159,   38,   39,   40,   41,  113,  359,   43,   44,
       43,   81,   41,   82,   82,   22,   46,   42,   47,   82,
       83,  114,   84,  115,  357,  159,  351,   47,   81,   84,
       82,   82,   48,  167,   85,  350,   82,   83,  168,   84,
      349,   81,   22,   82,   82,  114,   84,  115,  176,   82,
       83,   85,   84,   89,   44,   89,  160,  190,  167,   84,
      161,   91,  168,   92,   85,   22,   54,  188,  341,  284,

      177,  340,   92,  176,  284,  194,   55,   93,  338,  189,
      306,  160,  190,  195,  197,  161,  201,  207,   56,   57,
       58,   59,   60,   61,  177,   62,   63,  329,   64,  194,
      202,   65,   66,  189,   67,   68,   69,  195,  197,  328,
      327,  201,  207,   56,   57,   58,   59,   60,   61,  208,
       62,   63,   64,  322,  202,   65,   66,  209,   67,   68,
       69,   50,   51,   50,   50,   51,   50,  284,  321,   46,
      315,   47,   46,  208,   47,  271,   50,   51,   50,  212,
       47,  216,  209,   47,   46,   48,   47,  308,   48,   95,
       51,   95,  191,  191,  191,   47,  307,   91,  213,   92,

       48,   50,   51,   50,  212,  192,  216,  118,   92,   46,
      223,   47,  119,   93,  120,  193,  306,  219,  301,  298,
       47,  121,  213,  297,  289,   48,   98,   99,  100,  101,
      102,  103,  118,  104,  105,  223,  106,  119,  120,  107,
      108,  219,  109,  110,  111,  121,  231,  125,  126,  127,
      128,   98,   99,  100,  101,  102,  103,  281,  104,  105,
      106,  129,  224,  107,  108,  225,  109,  110,  111,   50,
       51,   50,  214,   81,  130,   82,   82,   46,  279,   47,
      226,   82,   83,  227,   84,  215,  129,  224,   47,  225,
      278,   84,   81,   48,   82,   82,   85,  214,  130,  139,

       82,   83,  140,   84,  275,  226,  141,  142,  227,  215,
       84,  228,  274,  271,  143,   85,  144,  265,  262,  260,
      259,  258,  256,  255,  139,  249,   81,  140,   82,   82,
      232,  141,  142,  248,   82,   83,  228,   84,  143,   81,
      144,   82,   82,   81,   84,   82,   82,   82,   83,   85,
       84,   82,   83,  230,   84,  232,  240,   84,  233,  245,
      234,   84,   85,  244,  243,   86,   85,   82,   82,  242,
       89,   44,   89,   82,   83,   87,   84,  230,   91,  236,
       92,  240,  233,   84,  234,   95,   51,   95,   85,   92,
      239,  241,  246,   91,   93,   92,  238,   95,   51,   95,

       50,   51,   50,  236,   92,   91,  247,   92,   46,   93,
       47,  251,   95,   51,   95,  241,   92,  246,  162,   47,
       91,   93,   92,  163,   48,  164,  169,  170,  171,  172,
      247,   92,  165,  250,  252,  251,   93,  257,  179,  254,
      173,  237,  261,  162,  180,  181,  263,  253,  163,  164,
      191,  191,  191,  174,  235,  264,  165,  269,  250,  252,
      268,  257,  179,  192,  254,  173,  261,  266,  180,  181,
      263,  253,  270,  193,  272,  273,  276,  174,  182,  264,
      277,  183,  269,  267,  268,  184,  185,  280,  282,  283,
      285,  293,  266,  186,  286,  187,  270,  287,  272,  273,

      276,  288,  292,  182,  277,  294,  183,  267,  290,  302,
      184,  185,  280,  282,  283,  285,  293,  186,  286,  187,
      295,  287,  296,  299,  291,  288,  292,  300,  303,  294,
      304,  231,  305,  290,  302,  309,  310,  311,  312,  229,
      313,  317,  318,  323,  295,  313,  296,  299,  291,  314,
      324,  300,  316,  303,  314,  304,  305,  316,  325,  309,
      310,  326,  311,  312,  320,  317,  318,  330,  323,  320,
      331,  332,  333,  222,  334,  324,  335,  336,  337,  339,
      221,  343,  345,  325,  346,  326,  343,  345,  348,  346,
      320,  330,  353,  348,  331,  320,  332,  333,  334,  354,

      335,  336,  352,  337,  339,  355,  356,  352,  313,  358,
      343,  361,  363,  345,  369,  343,  353,  314,  345,  369,
      316,  348,  371,  354,  375,  372,  348,  371,  374,  355,
      372,  356,  320,  374,  358,  361,  363,  377,  381,  369,
      384,  386,  374,  389,  369,  384,  386,  374,  375,  343,
      345,  390,  346,  393,  384,  386,  348,  220,  320,  384,
      386,  377,  394,  381,  395,  218,  217,  211,  389,  210,
      352,  206,  205,  204,  203,  390,  200,  393,  343,  199,
      198,  345,  369,  196,  112,  178,  394,  175,  395,  348,
      371,  157,  156,  372,   90,   51,  374,  155,   88,   82,

      135,  112,   97,   45,   94,   82,   88,  369,  384,  386,
      374,   76,   70,   52,  398,  398,  398,  398,  398,  398,
      398,  398,  384,  386,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   36,   36,   36,   36,   36,   36,   36,   36,
       36,   45,   45,   45,   45,  398,   45,   45,   80,   80,
       80,  398,   80,   90,   90,   90,   90,  398,   90,   90,
      319,  319,  398,  398,  319,  319,  319,  342,  342,  398,
      398,  342,  398,  342,  344,  344,  398,  398,  344,  398,
      344,  347,  347,  398,  398,  347,  398,  347,  368,  368,

      398,  398,  368,  398,  368,  373,  373,  398,  398,  373,
      398,  373,  383,  383,  398,  398,  383,  398,  383,  385,
      385,  398,  398,  385,  398,  385,   13,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398
    } ;

static yyconst flex_int16_t yy_chk[1102] =
    {   0,
        1,    1,    1,    1,   16,   16,   16,  403,    0,    1,
        0,    1,    1,   49,   49,   49,    0,    0,    0,    0,
        1,   53,    1,    0,    1,    1,    3,    4,    7,    5,
        6,    7,   25,   33,    8,    3,    4,    8,   26,   53,
        3,    4,   24,   28,  395,    3,    4,    5,    6,    1,
      394,  392,  391,  387,  386,   30,    7,   25,   33,   35,
        3,    4,    8,   26,    3,    4,   24,   64,   28,    3,
        4,    5,    6,    1,    2,    2,    2,    2,    9,   30,
       34,   10,  384,    2,   35,    2,    2,   60,    9,  382,
       65,   10,   64,  375,    2,  374,    2,    9,    2,    2,

       10,  370,   63,   58,   34,  369,    9,   58,  367,   10,
        9,   60,   72,   10,   65,   63,   15,   15,   15,   17,
       17,   17,    9,    2,   15,   10,   15,   17,   58,   17,
        9,  366,   58,   10,    9,   15,   72,   10,   17,   63,
       15,   71,   69,   17,  361,   73,  358,    2,   11,  356,
       11,   74,   11,   11,   69,   11,   11,  354,   11,   11,
       11,   11,   19,   19,   19,   77,   71,  351,   11,   73,
       19,   11,   19,   11,   36,   74,   36,   36,   69,   61,
       78,   19,   36,   36,   61,   36,   19,   75,  102,   67,
       77,   37,   36,   37,   37,   67,   67,   36,   11,   37,

       37,   37,   37,   79,   61,   78,  348,  345,   61,   37,
      343,   75,  102,   67,   37,  340,   99,  339,  337,   67,
       67,   11,   12,  335,   12,  333,   12,   12,   79,   12,
       12,   99,   12,   12,   12,   12,   57,  332,   43,   43,
       43,   38,   12,   38,   38,   12,   43,   12,   43,   38,
       38,   57,   38,   57,  330,   99,  320,   43,   39,   38,
       39,   39,   43,  103,   38,  318,   39,   39,  103,   39,
      317,   41,   12,   41,   41,   57,   39,   57,  106,   41,
       41,   39,   41,   44,   44,   44,  100,  114,  103,   41,
      100,   44,  103,   44,   41,   12,   20,  111,  312,  229,

      107,  311,   44,  106,  229,  116,   20,   44,  309,  111,
      306,  100,  114,  117,  119,  100,  123,  129,   20,   20,
       20,   20,   20,   20,  107,   20,   20,  294,   20,  116,
      124,   20,   20,  111,   20,   20,   20,  117,  119,  293,
      292,  123,  129,   20,   20,   20,   20,   20,   20,  130,
       20,   20,   20,  286,  124,   20,   20,  132,   20,   20,
       20,   45,   45,   45,   47,   47,   47,  229,  285,   45,
      280,   45,   47,  130,   47,  271,   50,   50,   50,  136,
       45,  139,  132,   47,   50,   45,   50,  270,   47,   51,
       51,   51,  115,  115,  115,   50,  269,   51,  137,   51,

       50,   52,   52,   52,  136,  115,  139,   59,   51,   52,
      147,   52,   59,   51,   59,  115,  268,  142,  261,  253,
       52,   59,  137,  252,  236,   52,   55,   55,   55,   55,
       55,   55,   59,   55,   55,  147,   55,   59,   59,   55,
       55,  142,   55,   55,   55,   59,  231,   62,   62,   62,
       62,   55,   55,   55,   55,   55,   55,  226,   55,   55,
       55,   62,  148,   55,   55,  149,   55,   55,   55,   70,
       70,   70,  138,   80,   62,   80,   80,   70,  224,   70,
      150,   80,   80,  151,   80,  138,   62,  148,   70,  149,
      223,   80,   81,   70,   81,   81,   80,  138,   62,   68,

       81,   81,   68,   81,  215,  150,   68,   68,  151,  138,
       81,  152,  214,  209,   68,   81,   68,  197,  192,  189,
      187,  186,  184,  183,   68,  177,   82,   68,   82,   82,
      159,   68,   68,  176,   82,   82,  152,   82,   68,   83,
       68,   83,   83,   84,   82,   84,   84,   83,   83,   82,
       83,   84,   84,  154,   84,  159,  167,   83,  160,  172,
      161,   84,   83,  171,  170,   86,   84,   86,   86,  169,
       89,   89,   89,   86,   86,   86,   86,  154,   89,  163,
       89,  167,  160,   86,  161,   90,   90,   90,   86,   89,
      166,  168,  173,   90,   89,   90,  165,   92,   92,   92,

       94,   94,   94,  163,   90,   92,  174,   92,   94,   90,
       94,  180,   95,   95,   95,  168,   92,  173,  101,   94,
       95,   92,   95,  101,   94,  101,  104,  104,  104,  104,
      174,   95,  101,  179,  181,  180,   95,  185,  109,  182,
      104,  164,  190,  101,  109,  109,  194,  181,  101,  101,
      191,  191,  191,  104,  162,  195,  101,  207,  179,  181,
      202,  185,  109,  191,  182,  104,  190,  201,  109,  109,
      194,  181,  208,  191,  212,  213,  216,  104,  110,  195,
      219,  110,  207,  201,  202,  110,  110,  225,  227,  228,
      230,  246,  201,  110,  232,  110,  208,  233,  212,  213,

      216,  234,  241,  110,  219,  247,  110,  201,  240,  263,
      110,  110,  225,  227,  228,  230,  246,  110,  232,  110,
      250,  233,  251,  254,  240,  234,  241,  257,  264,  247,
      266,  156,  267,  240,  263,  272,  273,  276,  277,  153,
      278,  282,  283,  287,  250,  278,  251,  254,  240,  279,
      288,  257,  281,  264,  279,  266,  267,  281,  290,  272,
      273,  291,  276,  277,  284,  282,  283,  295,  287,  284,
      296,  299,  300,  146,  302,  288,  303,  304,  305,  310,
      144,  313,  314,  290,  315,  291,  313,  314,  316,  315,
      319,  295,  323,  316,  296,  319,  299,  300,  302,  324,

      303,  304,  321,  305,  310,  325,  326,  321,  278,  331,
      342,  334,  336,  344,  346,  342,  323,  279,  344,  346,
      281,  347,  349,  324,  353,  350,  347,  349,  352,  325,
      350,  326,  284,  352,  331,  334,  336,  355,  363,  368,
      371,  372,  373,  377,  368,  371,  372,  373,  353,  313,
      314,  381,  315,  389,  383,  385,  316,  143,  319,  383,
      385,  355,  390,  363,  393,  141,  140,  134,  377,  133,
      321,  128,  127,  126,  125,  381,  122,  389,  342,  121,
      120,  344,  346,  118,  112,  108,  390,  105,  393,  347,
      349,   98,   97,  350,   93,   91,  352,   88,   87,   85,

       66,   56,   54,   48,   46,   42,   40,  368,  371,  372,
      373,   31,   21,   18,   13,    0,    0,    0,    0,    0,
        0,    0,  383,  385,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  400,  400,  400,  400,  400,  400,  400,
      400,  400,  401,  401,  401,  401,  401,  401,  401,  401,
      401,  402,  402,  402,  402,    0,  402,  402,  404,  404,
      404,    0,  404,  405,  405,  405,  405,    0,  405,  405,
      406,  406,    0,    0,  406,  406,  406,  407,  407,    0,
        0,  407,    0,  407,  408,  408,    0,    0,  408,    0,
      408,  409,  409,    0,    0,  409,    0,  409,  410,  410,

        0,    0,  410,    0,  410,  411,  411,    0,    0,  411,
        0,  411,  412,  412,    0,    0,  412,    0,  412,  413,
      413,    0,    0,  413,    0,  413,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,
      398,  398,  398,  398,  398,  398,  398,  398,  398,  398,

      398
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main_lexer.l"
/* Declaration section*/
#line 4 "main_lexer.l"
#include<stdio.h>
#include<string.h>
#include"ast_grammar.tab.h"
#include<bits/stdc++.h>
using namespace std;





#line 859 "lex.yy.c"

#define INITIAL 0
#define href 1
#define sizetag 2
#define table 3
#define src 4
#define comment 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 25 "main_lexer.l"

#line 1084 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 399 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1027 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 26 "main_lexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 32 "main_lexer.l"
{	
						//printf("HTML_S\n");
						return HTML_S;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "main_lexer.l"
{	
						//printf("HTML_E\n");
						return HTML_E;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 44 "main_lexer.l"
{	
						//printf("HEAD_S\n");
						return HEAD_S;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 50 "main_lexer.l"
{	
						//printf("HEAD_E\n");
						return HEAD_E;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "main_lexer.l"
{	
						//printf("BODY_S\n");
						return BODY_S;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 62 "main_lexer.l"
{	
						//printf("BODY_E\n");
						return BODY_E;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "main_lexer.l"
{
						//printf("TITLE_S\n");
						return TITLE_S;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 74 "main_lexer.l"
{
						//printf("TITLE_E\n");
						return TITLE_E;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 80 "main_lexer.l"
{
						//printf("HREF_S\n");
						BEGIN href;
						return HREF_S;
					}
	YY_BREAK

case 11:
YY_RULE_SETUP
#line 88 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_LINK;
									}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_TITLE;
									}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 113 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return HREF_NAME;
									}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 126 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 15:
YY_RULE_SETUP
#line 134 "main_lexer.l"
{	
						//printf("HREF_E\n");
						return HREF_E;
					}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 140 "main_lexer.l"
{
						//printf("FONT_S\n\n");

						BEGIN sizetag;
						return FONT_S;
					}
	YY_BREAK

case 17:
YY_RULE_SETUP
#line 149 "main_lexer.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										//printf("\nfinal%s\n",yylval.s);
										return FONT_SIZE;
									}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 161 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 19:
YY_RULE_SETUP
#line 167 "main_lexer.l"
{
						//printf("IMG Begin\n");
						BEGIN src;
						return IMG_S;
					}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 177 "main_lexer.l"
{
									//printf("SRC\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return IMG_SRC;
								}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 191 "main_lexer.l"
{
									//printf("WIDTH\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return IMG_WIDTH;
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 206 "main_lexer.l"
{
									//printf("HEIGHT\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);									
									return IMG_HEIGHT;
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 221 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 227 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK

case 25:
YY_RULE_SETUP
#line 235 "main_lexer.l"
{
						//printf("FIG_S");
						return FIG_S;
					}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 240 "main_lexer.l"
{
						//printf("FIG_E");
						return FIG_E;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 245 "main_lexer.l"
{
						//printf("FIGCAP_S");
						return FIGCAP_S;
					}		
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 250 "main_lexer.l"
{
						//printf("FIGCAP_E");
						return FIGCAP_E;
					}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 255 "main_lexer.l"
{
						//printf("FONT_E\n\n");
						return FONT_E;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 261 "main_lexer.l"
{
						//printf("CENTER_S\n");
						return CENTER_S;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 267 "main_lexer.l"
{
						//printf("CENTER_E\n");
						return CENTER_E;
					}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 273 "main_lexer.l"
{
						//printf("DIV_S\n");
						return DIV_S;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 279 "main_lexer.l"
{
						//printf("DIV_E\n");
						return DIV_E;
					}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 287 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 292 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 297 "main_lexer.l"
{
						//printf("P_S\n");
						return P_S;
					}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 303 "main_lexer.l"
{
						//printf("P_E\n");
						return P_E;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 309 "main_lexer.l"
{
						//printf("H1_S\n");
						return H1_S;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 315 "main_lexer.l"
{
						//printf("H1_E\n");
						return H1_E;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 321 "main_lexer.l"
{
						//printf("H2_S\n");
						return H2_S;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 327 "main_lexer.l"
{
						//printf("H2_E\n");
						return H2_E;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 333 "main_lexer.l"
{
						//printf("H3_S\n");
						return H3_S;
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 338 "main_lexer.l"
{
						//printf("H3_E\n");
						return H3_E;
					}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 343 "main_lexer.l"
{
						//printf("H4_S\n");
						return H4_S;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 349 "main_lexer.l"
{
						//printf("H4_E\n");
						return H4_E;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 355 "main_lexer.l"
{
						//printf("UL_S\n");
						return UL_S;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 361 "main_lexer.l"
{
						//printf("UL_E\n");
						return UL_E;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 366 "main_lexer.l"
{
						//printf("LI_S\n");
						return LI_S;
					}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 372 "main_lexer.l"
{
						//printf("LI_E\n");
						return LI_E;
					}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 377 "main_lexer.l"
{
						//printf("OL_S\n");
						return OL_S;
					}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 383 "main_lexer.l"
{
						//printf("OL_E\n");
						return OL_E;
					}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 388 "main_lexer.l"
{
						//printf("DT_S\n");
						return DT_S;
					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 394 "main_lexer.l"
{
						//printf("DT_E\n");
						return DT_E;
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 399 "main_lexer.l"
{
						//printf("DL_S\n");
						return DL_S;
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 405 "main_lexer.l"
{
						//printf("DL_E\n");
						return DL_E;
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 410 "main_lexer.l"
{
						//printf("DD_S\n");
						return DD_S;
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 416 "main_lexer.l"
{
						//printf("DD_E\n");
						return DD_E;
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 422 "main_lexer.l"
{
						//printf("U_S\n");
						return U_S;
					}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 427 "main_lexer.l"
{
						//printf("U_E\n");
						return U_E;
					}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 432 "main_lexer.l"
{
						//printf("B_S\n");
						return B_S;
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 437 "main_lexer.l"
{
						//printf("B_E\n");
						return B_E;
					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 442 "main_lexer.l"
{
						//printf("I_S\n");
						return I_S;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 447 "main_lexer.l"
{
						//printf("I_E\n");
						return I_E;
					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 452 "main_lexer.l"
{
						//printf("EM_S\n");
						return EM_S;
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 457 "main_lexer.l"
{
						//printf("EM_E\n");
						return EM_E;
					}					
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 462 "main_lexer.l"
{
						//printf("TT_S\n");
						return TT_S;
					}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 467 "main_lexer.l"
{
						//printf("TT_E\n");
						return TT_E;
					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 473 "main_lexer.l"
{
						//printf("STRONG_S\n");
						return STRONG_S;
					}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 478 "main_lexer.l"
{
						//printf("STRONG_E\n");
						return STRONG_E;
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 484 "main_lexer.l"
{
						//printf("SMALL_S\n");
						return SMALL_S;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 489 "main_lexer.l"
{
						//printf("SMALL_E\n");
						return SMALL_E;
					}			
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 496 "main_lexer.l"
{
						//printf("SUB_S\n");
						return SUB_S;
					}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 502 "main_lexer.l"
{
						//printf("SUB_E\n");
						return SUB_E;
					}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 507 "main_lexer.l"
{
						//printf("SUP_S\n");
						return SUP_S;
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 513 "main_lexer.l"
{
						//printf("SUP_E\n");
						return SUP_E;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 518 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN table;
						return TABLE_S;
					}
	YY_BREAK

case 77:
YY_RULE_SETUP
#line 526 "main_lexer.l"
{
									//printf("BORDER i\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									//printf("\nfinal%s\n",yylval.s);
									return TABLE_BORDER;
								}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 540 "main_lexer.l"
{
										BEGIN 0;
								}	
	YY_BREAK

case 79:
YY_RULE_SETUP
#line 548 "main_lexer.l"
{
						//printf("TABLE_E\n");
						return TABLE_E;
					}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 554 "main_lexer.l"
{
						//printf("CAPTION_S\n");
						return CAPTION_S;
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 560 "main_lexer.l"
{
						//printf("CAPTION_E\n");
						return CAPTION_E;
					}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 566 "main_lexer.l"
{
						//printf("TH_S\n");
						return TH_S;
					}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 572 "main_lexer.l"
{
						//printf("TH_E\n");
						return TH_E;
					}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 578 "main_lexer.l"
{
						//printf("TR_S\n");
						return TR_S;
					}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 584 "main_lexer.l"
{
						//printf("TR_E\n");
						return TR_E;
					}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 590 "main_lexer.l"
{
						//printf("TD_S\n");
						return TD_S;
					}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 596 "main_lexer.l"
{
						//printf("TD_E\n");
						return TD_E;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 602 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN comment;
						//return TABLE_S;
					}
	YY_BREAK

case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 610 "main_lexer.l"
{
										//printf("Comment %s Comment_end\n",yytext);
										yylval.s = (char *)malloc(100);	
										yylval.s = yytext;
										return COMMENT;
										
									}
	YY_BREAK
case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 617 "main_lexer.l"
{
										BEGIN 0;
									}
	YY_BREAK

case 91:
YY_RULE_SETUP
#line 625 "main_lexer.l"
{	
						//printf("GreekL -%s\n",yytext);
						yylval.s = strdup(yytext);
						return GREEK;
					}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 631 "main_lexer.l"
{
						//printf("Contents -%s\n",yytext);
						
						yylval.s = strdup(yytext);
						/*
						string str(yylval.s);
						char find_vec[] = {'_','#','%','$','&','{','}','~','^'};
						vector<string> replace_vec = {"\\_","\\#","\\%","\\$","\\&","\\{","\\}","\\sim","\\hat{}"};
						int pos;
						string str1(str);
						string str2("");
						for(int i=0;i<replace_vec.size();i++)
						{
							for (int j=0;j<str1.length();j++)
							{
								if(str1[j]==find_vec[i])
									str2+=replace_vec[i];
								else
									str2+=str1[j];
							}
							str1=str2;
							str2="";
									
	   					}
   						strcpy(yylval.s,str1.c_str());*/
						return DATA;
					}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 665 "main_lexer.l"
;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 668 "main_lexer.l"
ECHO;
	YY_BREAK
#line 2001 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(href):
case YY_STATE_EOF(sizetag):
case YY_STATE_EOF(table):
case YY_STATE_EOF(src):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 399 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 399 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 398);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 668 "main_lexer.l"


  
int yywrap()
{
	return 1;	
} 
/*int main(int argc,char *argv[])
{
	yyin = fopen(argv[1],"r");
	//tex_file = fopen(argv[2],"w+");
	yylex();
}  */   


