
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[384] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
       93,   91,    1,    1,   91,   91,   91,   91,   91,   92,
       15,   92,   92,   92,   19,   92,   79,   92,   92,   25,
       92,   92,   92,    1,    1,   89,   89,    0,    1,   89,
        0,    0,    0,    0,    0,    0,   11,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        1,   89,   89,    0,   89,   90,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   11,   61,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       63,    0,    0,    0,   37,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   59,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   16,   62,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   64,    0,    0,   38,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   60,    0,    0,    0,
        0,   36,    0,    0,   57,    0,   55,   53,   65,    0,
        0,   39,   41,   43,   45,    0,    0,   20,   49,   51,
        0,    0,    0,    0,    0,   87,   83,    0,   85,   67,

       47,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   58,    0,   56,   54,   66,    0,    0,
       40,   42,   44,   46,    0,    0,   50,   52,    0,    0,
        0,    0,    0,   88,   84,    0,   86,   68,   48,    0,
       35,    0,    0,   33,    0,    0,   17,    0,    0,   20,
        0,    0,   73,   75,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   34,    0,
        0,    0,    0,    0,    0,    0,   74,   76,    0,    0,
        7,    0,    0,    0,    0,   17,    5,    3,    0,    0,
       77,    0,    0,    0,    0,    0,    0,    0,    0,   21,

        0,    0,    8,    0,    0,    0,    0,   30,    6,    4,
        0,    0,    0,    0,    0,    0,    0,    0,   71,    0,
       77,    9,    0,   12,    0,   14,    0,    0,   18,    0,
        0,   21,    0,    0,    0,    0,    0,    0,   72,    0,
       80,   10,    0,   31,    0,   26,   69,   12,   14,    0,
       13,   18,    0,    0,    0,   22,    0,    0,   32,    0,
       27,   70,   81,    0,   13,    0,   78,    0,   23,   22,
        0,   82,    0,    0,   78,   23,    2,    0,    0,    0,
       28,   29,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,    1,
        1,    1,    1,   11,    1,   12,   13,   14,   15,   16,
       17,   18,   14,   14,   14,   14,   14,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   14,   14,   34,   35,   36,   37,   38,
       14,   39,   40,   41,   42,   43,   44,   14,   45,   46,
        1,    1,    1,    1,    1,    1,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   14,   14,   56,   57,   58,
       59,   60,   14,   61,   62,   63,   64,   65,   66,   14,
       67,   68,    1,   69,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[70] =
    {   0,
        1,    2,    2,    3,    4,    5,    4,    1,    1,    5,
        4,    5,    6,    5,    5,    5,    5,    5,    5,    4,
        1,    5,    7,    4,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    6
    } ;

static yyconst flex_uint16_t yy_base[398] =
    {   0,
        0,   69,    2,    3,    5,    6,    4,   10,   51,   62,
      836,  837,   38,    3,   85,    7,   96,  134,  827,  837,
      837,   15,   12,   46,  837,   70,  837,   67,  811,  837,
       81,   72,   79,  119,  133,  197,  200,  825,   12,  203,
      214,  129,  167,  824,  101,  214,  819,  244,  206,  251,
      113,  238,  271,  123,  122,  139,  796,  267,  310,  226,
      315,  181,  188,  187,  190,  198,  837,  239,  264,  270,
      342,  365,  376,  807,  379,  317,  262,  788,  273,  311,
      364,  276,  315,  392,  784,  292,  316,  780,  360,  431,
      362,  795,  837,  356,  409,  355,  358,  772,  361,  745,

      744,  743,  394,  392,  742,  740,  739,  738,  404,  395,
      837,  400,  737,  734,  837,  410,  397,  423,  412,  733,
      732,  399,  731,  729,  837,  727,  414,  416,  412,  425,
      437,  438,  727,  432,  447,  837,  837,  447,  439,  443,
      725,  437,  724,  723,  722,  451,  448,  720,  718,  717,
      716,  463,  454,  837,  715,  713,  837,  465,  454,  479,
      472,  712,  710,  459,  709,  707,  837,  705,  458,  505,
      704,  837,  472,  473,  837,  701,  837,  837,  837,  489,
      478,  837,  837,  837,  837,  493,  489,  719,  837,  837,
      490,  489,  699,  695,  495,  837,  837,  496,  837,  837,

      837,  695,  694,  503,  693,  504,  502,   45,  505,  499,
      497,  503,  506,  837,  691,  837,  837,  837,  523,  508,
      837,  837,  837,  837,  529,  524,  837,  837,  526,  524,
      690,  638,  529,  837,  837,  533,  837,  837,  837,  633,
      837,  535,  541,  837,  548,  535,  639,  599,  425,  438,
      541,  540,  837,  837,  548,  549,  144,  578,  419,  595,
      542,  545,  596,  417,  546,  414,  560,  565,  837,  579,
      568,  411,  376,  363,  575,  574,  837,  837,  582,  583,
      837,  577,  578,  580,  590,  371,  837,  837,  340,  589,
      357,  336,  615,  617,  618,  638,  334,  333,  639,  319,

      640,  592,  837,  598,  598,  600,  622,  837,  837,  837,
      293,  622,  292,  281,  618,  272,  614,  267,  837,  257,
      230,  837,  652,  229,  657,  226,  660,  662,  225,  668,
      673,  218,  675,  640,  635,  197,  639,  196,  837,  169,
      837,  837,  146,  837,  649,  837,  837,  161,  152,  682,
      148,  138,  684,  689,  690,  123,    0,   96,  837,  656,
      837,  837,  837,  660,  114,  695,  111,  700,   82,   80,
       40,  837,  661,  667,   49,   44,  837,  676,   24,    9,
      837,  837,  837,  769,  776,  782,  784,  788,  791,  795,
      799,  803,  807,  811,  815,  819,  825

    } ;

static yyconst flex_int16_t yy_def[398] =
    {   0,
      384,  384,  385,  385,  385,  385,  385,  385,  385,  385,
      383,  383,  386,  383,  386,  387,  386,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  386,  388,  386,  386,  383,  383,  386,
      388,  387,  387,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      386,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      388,  388,  388,  383,  388,  387,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  389,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  390,  391,  383,  392,  383,  383,  389,  383,

      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  390,  383,  391,  383,  393,  392,  383,  383,
      383,  383,  394,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  393,
      383,  383,  395,  396,  394,  383,  397,  383,  383,  383,
      383,  383,  383,  383,  383,  395,  383,  396,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,    0,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383

    } ;

static yyconst flex_uint16_t yy_nxt[907] =
    {   0,
       12,   13,   14,   13,   39,   39,   39,   12,   16,  383,
       17,   17,   12,   39,   39,   39,  383,   43,   43,  383,
       18,  383,   12,   19,   21,   21,   27,   25,   25,   28,
       44,  382,   27,   22,   22,   28,   63,   23,   23,   34,
       35,   34,   24,   24,   26,   26,  381,  376,   37,   37,
      263,   28,  375,   62,  263,   22,   22,   28,   63,   23,
       23,   38,  377,   29,   24,   24,   26,   26,   12,   12,
       13,   14,   13,   30,   29,   62,   12,   16,   64,   17,
       17,   12,   31,  370,   30,  376,   40,   41,   40,   18,
       32,   12,   19,   31,   33,   37,   37,   40,   41,   40,

       64,   32,   65,   66,   31,   33,   37,   37,   38,   68,
       69,   70,   32,  263,  375,   31,   33,  365,  372,   38,
       34,   35,   34,   32,   65,   66,  370,   33,   77,   37,
       37,   68,   69,   70,   71,   35,   71,   12,   45,   43,
       43,  352,   38,   73,   73,  111,   46,  102,   76,  293,
       77,  365,   44,  293,  113,  349,   74,  112,   47,   48,
       49,   50,   51,   52,  348,   53,   54,   55,  363,  102,
       56,   57,  114,   58,   59,   60,  113,   43,   43,  112,
       47,   48,   49,   50,   51,   52,   76,   53,   54,   55,
       44,  362,   56,   57,  114,   58,   59,   60,   40,   41,

       40,   40,   41,   40,   40,   41,   40,   37,   37,  127,
       37,   37,  293,   37,   37,   75,   41,   75,  361,  359,
       38,  332,  128,   38,   73,   73,   38,  129,  352,  349,
       96,  127,  348,  321,   97,  130,  131,   74,   78,   79,
       80,   81,   82,   83,  128,   84,   85,   86,  125,  129,
       87,   88,   96,   89,   90,   91,   97,  130,  131,  126,
       78,   79,   80,   81,   82,   83,   93,   84,   85,   86,
      103,  132,   87,   88,  104,   89,   90,   91,   98,  347,
       94,  126,   95,   99,  100,  105,  106,  107,  108,  346,
      133,  101,  103,  132,  344,  137,  104,  134,  135,  109,

       98,  116,   94,  342,   95,   99,  100,  117,  118,  138,
      145,  110,  133,  101,  341,  339,   40,   41,   40,  134,
      135,  109,  332,  116,  155,   37,   37,   43,   43,  117,
      118,  138,  145,  110,  119,  139,   76,  120,   38,  140,
       44,  121,  122,   71,   35,   71,  155,  146,  123,  156,
      124,  147,   73,   73,  331,  330,  119,  139,  322,  120,
      321,  140,  319,  121,  122,   74,   75,   41,   75,  146,
      123,  156,  124,  147,  286,   73,   73,   75,   41,   75,
       75,   41,   75,  169,  167,  310,   73,   73,   74,   73,
       73,  141,  173,  174,  158,  168,  142,  143,  309,   74,

      159,  160,   74,  176,  144,  169,  148,  149,  150,  151,
      170,  170,  170,  141,  173,  174,  158,  168,  142,  143,
      152,  171,  159,  160,  180,  176,  144,  181,  186,  187,
      188,  172,  153,  308,  191,  192,  303,  195,  301,  198,
      295,  250,  152,  202,  203,  204,  180,  288,  193,  181,
      186,  187,  188,  205,  153,  161,  191,  192,  162,  195,
      194,  198,  163,  164,  206,  202,  203,  204,  207,  165,
      193,  166,  209,  210,  211,  205,  212,  161,  213,  215,
      162,  219,  194,  220,  163,  164,  206,  225,  226,  229,
      207,  165,  230,  166,  209,  210,  211,  233,  212,  236,

      213,  215,  240,  219,  231,  220,  170,  170,  170,  225,
      226,  229,  242,  243,  230,  245,  232,  171,  247,  233,
      248,  236,  249,  251,  240,  252,  231,  172,  255,  256,
      246,  259,  261,  262,  242,  243,  264,  245,  232,  265,
      247,  266,  248,  267,  249,  251,  268,  252,  272,  270,
      255,  256,  246,  259,  261,  262,  273,  274,  264,  275,
      276,  265,  279,  266,  271,  267,  280,  282,  268,  283,
      272,  270,  284,  285,  289,  290,  291,  292,  273,  274,
      297,  275,  276,  294,  279,  298,  271,  294,  280,  282,
      302,  283,  304,  305,  284,  285,  289,  290,  291,  292,

      296,  300,  297,  306,  296,  300,  307,  298,  311,  312,
      313,  314,  302,  315,  304,  305,  316,  317,  318,  320,
      324,  287,  326,  327,  324,  306,  326,  327,  307,  334,
      311,  312,  313,  314,  335,  315,  336,  337,  316,  317,
      318,  320,  286,  329,  300,  333,  294,  329,  300,  333,
      338,  334,  340,  343,  345,  281,  335,  324,  336,  337,
      278,  324,  326,  296,  300,  351,  326,  329,  357,  351,
      358,  329,  338,  353,  340,  343,  345,  353,  354,  360,
      356,  364,  354,  324,  356,  326,  327,  351,  373,  367,
      357,  351,  358,  367,  369,  356,  374,  378,  369,  356,

      367,  360,  379,  364,  367,  369,  329,  300,  333,  369,
      373,  380,  277,  269,  260,  258,  257,  254,  374,  378,
      324,  253,  250,  244,  379,  326,  241,  239,  351,  238,
      329,  237,  235,  380,  234,  228,  353,  227,  224,  223,
      222,  354,  221,  356,  218,  217,  216,  214,  208,  201,
      351,  200,  367,  199,  197,  196,  190,  369,  356,  189,
      185,  184,  183,  367,  182,  179,  178,  177,  369,   15,
       15,   15,   15,   15,   15,   15,   20,   20,   20,   20,
       20,   20,   20,   36,   36,   36,   36,   42,   42,   72,
       72,   72,   72,  299,  175,  299,  299,  323,   92,  323,

      323,  325,  157,  325,  325,  328,  154,  328,  328,  350,
      136,  350,  350,  355,   72,  355,  355,  366,  115,  366,
      366,  368,   92,  368,  368,  371,  371,  371,  371,  371,
      371,   42,   36,   67,   61,  383,   11,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383
    } ;

static yyconst flex_int16_t yy_chk[907] =
    {   0,
        1,    1,    1,    1,   14,   14,   14,    1,    1,    0,
        1,    1,    1,   39,   39,   39,    0,   16,   16,    0,
        1,    0,    1,    1,    3,    4,    7,    5,    6,    7,
       16,  380,    8,    3,    4,    8,   23,    3,    4,   13,
       13,   13,    3,    4,    5,    6,  379,  376,   13,   13,
      208,    7,  375,   22,  208,    3,    4,    8,   23,    3,
        4,   13,  371,    9,    3,    4,    5,    6,    1,    2,
        2,    2,    2,    9,   10,   22,    2,    2,   24,    2,
        2,    2,    9,  370,   10,  369,   15,   15,   15,    2,
        9,    2,    2,   10,    9,   15,   15,   17,   17,   17,

       24,   10,   26,   28,    9,   10,   17,   17,   15,   31,
       32,   33,    9,  208,  367,   10,    9,  365,  358,   17,
       34,   34,   34,   10,   26,   28,  356,   10,   45,   34,
       34,   31,   32,   33,   35,   35,   35,    2,   18,   42,
       42,  352,   34,   35,   35,   54,   18,   51,   42,  257,
       45,  351,   42,  257,   55,  349,   35,   54,   18,   18,
       18,   18,   18,   18,  348,   18,   18,   18,  343,   51,
       18,   18,   56,   18,   18,   18,   55,   43,   43,   54,
       18,   18,   18,   18,   18,   18,   43,   18,   18,   18,
       43,  340,   18,   18,   56,   18,   18,   18,   36,   36,

       36,   37,   37,   37,   40,   40,   40,   36,   36,   62,
       37,   37,  257,   40,   40,   41,   41,   41,  338,  336,
       36,  332,   63,   37,   41,   41,   40,   64,  329,  326,
       49,   62,  324,  321,   49,   65,   66,   41,   46,   46,
       46,   46,   46,   46,   63,   46,   46,   46,   60,   64,
       46,   46,   49,   46,   46,   46,   49,   65,   66,   60,
       46,   46,   46,   46,   46,   46,   48,   46,   46,   46,
       52,   68,   46,   46,   52,   46,   46,   46,   50,  320,
       48,   60,   48,   50,   50,   53,   53,   53,   53,  318,
       69,   50,   52,   68,  316,   79,   52,   70,   77,   53,

       50,   58,   48,  314,   48,   50,   50,   58,   58,   79,
       82,   53,   69,   50,  313,  311,   61,   61,   61,   70,
       77,   53,  300,   58,   86,   61,   61,   76,   76,   58,
       58,   79,   82,   53,   59,   80,   76,   59,   61,   80,
       76,   59,   59,   71,   71,   71,   86,   83,   59,   87,
       59,   83,   71,   71,  298,  297,   59,   80,  292,   59,
      291,   80,  289,   59,   59,   71,   72,   72,   72,   83,
       59,   87,   59,   83,  286,   72,   72,   73,   73,   73,
       75,   75,   75,   94,   91,  274,   73,   73,   72,   75,
       75,   81,   96,   97,   89,   91,   81,   81,  273,   73,

       89,   89,   75,   99,   81,   94,   84,   84,   84,   84,
       95,   95,   95,   81,   96,   97,   89,   91,   81,   81,
       84,   95,   89,   89,  103,   99,   81,  104,  109,  110,
      112,   95,   84,  272,  116,  117,  266,  119,  264,  122,
      259,  250,   84,  127,  128,  129,  103,  249,  118,  104,
      109,  110,  112,  130,   84,   90,  116,  117,   90,  119,
      118,  122,   90,   90,  131,  127,  128,  129,  132,   90,
      118,   90,  134,  135,  138,  130,  139,   90,  140,  142,
       90,  146,  118,  147,   90,   90,  131,  152,  153,  158,
      132,   90,  159,   90,  134,  135,  138,  161,  139,  164,

      140,  142,  169,  146,  160,  147,  170,  170,  170,  152,
      153,  158,  173,  174,  159,  180,  160,  170,  181,  161,
      186,  164,  187,  191,  169,  192,  160,  170,  195,  198,
      180,  204,  206,  207,  173,  174,  209,  180,  160,  210,
      181,  211,  186,  212,  187,  191,  213,  192,  220,  219,
      195,  198,  180,  204,  206,  207,  225,  226,  209,  229,
      230,  210,  233,  211,  219,  212,  236,  242,  213,  243,
      220,  219,  245,  246,  251,  252,  255,  256,  225,  226,
      261,  229,  230,  258,  233,  262,  219,  258,  236,  242,
      265,  243,  267,  268,  245,  246,  251,  252,  255,  256,

      260,  263,  261,  270,  260,  263,  271,  262,  275,  276,
      279,  280,  265,  282,  267,  268,  283,  284,  285,  290,
      293,  248,  294,  295,  293,  270,  294,  295,  271,  302,
      275,  276,  279,  280,  304,  282,  305,  306,  283,  284,
      285,  290,  247,  296,  299,  301,  258,  296,  299,  301,
      307,  302,  312,  315,  317,  240,  304,  323,  305,  306,
      232,  323,  325,  260,  263,  327,  325,  328,  334,  327,
      335,  328,  307,  330,  312,  315,  317,  330,  331,  337,
      333,  345,  331,  293,  333,  294,  295,  350,  360,  353,
      334,  350,  335,  353,  354,  355,  364,  373,  354,  355,

      366,  337,  374,  345,  366,  368,  296,  299,  301,  368,
      360,  378,  231,  215,  205,  203,  202,  194,  364,  373,
      323,  193,  188,  176,  374,  325,  171,  168,  327,  166,
      328,  165,  163,  378,  162,  156,  330,  155,  151,  150,
      149,  331,  148,  333,  145,  144,  143,  141,  133,  126,
      350,  124,  353,  123,  121,  120,  114,  354,  355,  113,
      108,  107,  106,  366,  105,  102,  101,  100,  368,  384,
      384,  384,  384,  384,  384,  384,  385,  385,  385,  385,
      385,  385,  385,  386,  386,  386,  386,  387,  387,  388,
      388,  388,  388,  389,   98,  389,  389,  390,   92,  390,

      390,  391,   88,  391,  391,  392,   85,  392,  392,  393,
       78,  393,  393,  394,   74,  394,  394,  395,   57,  395,
      395,  396,   47,  396,  396,  397,  397,  397,  397,  397,
      397,   44,   38,   29,   19,   11,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  383,

      383,  383,  383,  383,  383,  383
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexback.l"
/* Declaration section*/
#line 4 "lexback.l"
#include<stdio.h>
#include<string.h>
#include"y.tab.h"




#line 805 "lex.yy.c"

#define INITIAL 0
#define href 1
#define sizetag 2
#define table 3
#define src 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 21 "lexback.l"

#line 1029 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 384 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 837 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 22 "lexback.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 23 "lexback.l"
{
						return DOCTYPE;
					}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 26 "lexback.l"
{	
						printf("HTML_S\n");
						return HTML_S;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "lexback.l"
{	
						printf("HTML_E\n");
						return HTML_E;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "lexback.l"
{	
						printf("HEAD_S\n");
						return HEAD_S;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "lexback.l"
{	
						printf("HEAD_E\n");
						return HEAD_E;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "lexback.l"
{	
						printf("BODY_S\n");
						return BODY_S;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "lexback.l"
{	
						printf("BODY_E\n");
						return BODY_E;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 62 "lexback.l"
{
						printf("TITLE_S\n");
						return TITLE_S;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "lexback.l"
{
						printf("TITLE_E\n");
						return TITLE_E;
					}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "lexback.l"
{
						printf("HREF_S\n");
						BEGIN href;
						return HREF_S;
					}
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 82 "lexback.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										printf("\nfinal%s\n",yylval.s);
										return HREF_LINK;
									}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 95 "lexback.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										printf("\nfinal%s\n",yylval.s);
										return HREF_TITLE;
									}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 107 "lexback.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										printf("\nfinal%s\n",yylval.s);
										return HREF_NAME;
									}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 120 "lexback.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 16:
YY_RULE_SETUP
#line 128 "lexback.l"
{	
						printf("HREF_E\n");
						return HREF_E;
					}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 134 "lexback.l"
{
						printf("FONT_S\n\n");

						BEGIN sizetag;
						return FONT_S;
					}
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 143 "lexback.l"
{
										char *p = yytext; 
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										if(sscanf(p,"%*[^']'%[^']'",t)==1)
											strcat(yylval.s,t);
										else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
											strcat(yylval.s,t1);
										printf("\nfinal%s\n",yylval.s);
										return FONT_SIZE;
									}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 155 "lexback.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 161 "lexback.l"
{
						printf("IMG Begin\n");
						BEGIN src;
						return IMG_S;
					}
	YY_BREAK

case 21:
YY_RULE_SETUP
#line 171 "lexback.l"
{
									printf("SRC\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									printf("\nfinal%s\n",yylval.s);
									return IMG_SRC;
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 185 "lexback.l"
{
									printf("WIDTH\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									printf("\nfinal%s\n",yylval.s);
									return IMG_WIDTH;
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 200 "lexback.l"
{
									printf("HEIGHT\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									printf("\nfinal%s\n",yylval.s);									
									return IMG_HEIGHT;
								}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 215 "lexback.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 221 "lexback.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 229 "lexback.l"
{
						printf("FIG_S");
						return FIG_S;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 234 "lexback.l"
{
						printf("FIG_E");
						return FIG_E;
					}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "lexback.l"
{
						printf("FIGCAP_S");
						return FIGCAP_S;
					}		
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 244 "lexback.l"
{
						printf("FIGCAP_E");
						return FIGCAP_E;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 249 "lexback.l"
{
						printf("FONT_E\n\n");
						return FONT_E;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 255 "lexback.l"
{
						printf("CENTER_S\n");
						return CENTER_S;
					}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 261 "lexback.l"
{
						printf("CENTER_E\n");
						return CENTER_E;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 267 "lexback.l"
{
						printf("DIV_S\n");
						return DIV_S;
					}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 273 "lexback.l"
{
						printf("DIV_E\n");
						return DIV_E;
					}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 281 "lexback.l"
{
						printf("BR\n");
						return BR;
					}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 286 "lexback.l"
{
						printf("BR\n");
						return BR;
					}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 291 "lexback.l"
{
						printf("P_S\n");
						return P_S;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 297 "lexback.l"
{
						printf("P_E\n");
						return P_E;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 303 "lexback.l"
{
						printf("H1_S\n");
						return H1_S;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 309 "lexback.l"
{
						printf("H1_E\n");
						return H1_E;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 315 "lexback.l"
{
						printf("H2_S\n");
						return H2_S;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 321 "lexback.l"
{
						printf("H2_E\n");
						return H2_E;
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 327 "lexback.l"
{
						printf("H3_S\n");
						return H3_S;
					}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 332 "lexback.l"
{
						printf("H3_E\n");
						return H3_E;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 337 "lexback.l"
{
						printf("H4_S\n");
						return H4_S;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 343 "lexback.l"
{
						printf("H4_E\n");
						return H4_E;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 349 "lexback.l"
{
						printf("UL_S\n");
						return UL_S;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 355 "lexback.l"
{
						printf("UL_E\n");
						return UL_E;
					}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 360 "lexback.l"
{
						printf("LI_S\n");
						return LI_S;
					}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 366 "lexback.l"
{
						printf("LI_E\n");
						return LI_E;
					}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 371 "lexback.l"
{
						printf("OL_S\n");
						return OL_S;
					}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 377 "lexback.l"
{
						printf("OL_E\n");
						return OL_E;
					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 382 "lexback.l"
{
						printf("DT_S\n");
						return DT_S;
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 388 "lexback.l"
{
						printf("DT_E\n");
						return DT_E;
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 393 "lexback.l"
{
						printf("DL_S\n");
						return DL_S;
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 399 "lexback.l"
{
						printf("DL_E\n");
						return DL_E;
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 404 "lexback.l"
{
						printf("DD_S\n");
						return DD_S;
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 410 "lexback.l"
{
						printf("DD_E\n");
						return DD_E;
					}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 416 "lexback.l"
{
						printf("U_S\n");
						return U_S;
					}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 421 "lexback.l"
{
						printf("U_E\n");
						return U_E;
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 426 "lexback.l"
{
						printf("B_S\n");
						return B_S;
					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 431 "lexback.l"
{
						printf("B_E\n");
						return B_E;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 436 "lexback.l"
{
						printf("I_S\n");
						return I_S;
					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 441 "lexback.l"
{
						printf("I_E\n");
						return I_E;
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 446 "lexback.l"
{
						printf("EM_S\n");
						return EM_S;
					}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 451 "lexback.l"
{
						printf("EM_E\n");
						return EM_E;
					}					
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 456 "lexback.l"
{
						printf("TT_S\n");
						return TT_S;
					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 461 "lexback.l"
{
						printf("TT_E\n");
						return TT_E;
					}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 467 "lexback.l"
{
						printf("STRONG_S\n");
						return STRONG_S;
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 472 "lexback.l"
{
						printf("STRONG_E\n");
						return STRONG_E;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 478 "lexback.l"
{
						printf("SMALL_S\n");
						return SMALL_S;
					}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 483 "lexback.l"
{
						printf("SMALL_E\n");
						return SMALL_E;
					}			
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 490 "lexback.l"
{
						printf("SUB_S\n");
						return SUB_S;
					}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 496 "lexback.l"
{
						printf("SUB_E\n");
						return SUB_E;
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 501 "lexback.l"
{
						printf("SUP_S\n");
						return SUP_S;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 507 "lexback.l"
{
						printf("SUP_E\n");
						return SUP_E;
					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 512 "lexback.l"
{
						printf("TABLE_S\n");
						BEGIN table;
						return TABLE_S;
					}
	YY_BREAK

case 78:
YY_RULE_SETUP
#line 520 "lexback.l"
{
									printf("BORDER i\n\n");
									char *p = yytext; 
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									if(sscanf(p,"%*[^']'%[^']'",t)==1)
										strcat(yylval.s,t);
									else if(sscanf(p, "%*[^\"]\"%[^\"]", t1)==1)
										strcat(yylval.s,t1);
									printf("\nfinal%s\n",yylval.s);
									return TABLE_BORDER;
								}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 534 "lexback.l"
{
										BEGIN 0;
								}	
	YY_BREAK

case 80:
YY_RULE_SETUP
#line 542 "lexback.l"
{
						printf("TABLE_E\n");
						return TABLE_E;
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 548 "lexback.l"
{
						printf("CAPTION_S\n");
						return CAPTION_S;
					}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 554 "lexback.l"
{
						printf("CAPTION_E\n");
						return CAPTION_E;
					}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 560 "lexback.l"
{
						printf("TH_S\n");
						return TH_S;
					}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 566 "lexback.l"
{
						printf("TH_E\n");
						return TH_E;
					}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 572 "lexback.l"
{
						printf("TR_S\n");
						return TR_S;
					}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 578 "lexback.l"
{
						printf("TR_E\n");
						return TR_E;
					}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 584 "lexback.l"
{
						printf("TD_S\n");
						return TD_S;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 590 "lexback.l"
{
						printf("TD_E\n");
						return TD_E;
					}
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 599 "lexback.l"
{
						printf("Contents -%s\n",yytext);
						yylval.s = strdup(yytext);
						return DATA;
					}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 607 "lexback.l"
{	
						printf("GreekL -%s\n",yytext);
						yylval.s = strdup(yytext);
						return GREEK;
					}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 614 "lexback.l"
;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 617 "lexback.l"
ECHO;
	YY_BREAK
#line 1901 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(href):
case YY_STATE_EOF(sizetag):
case YY_STATE_EOF(table):
case YY_STATE_EOF(src):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 384 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 384 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 383);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 617 "lexback.l"


  
int yywrap()
{
	return 1;	
} 
/*int main(int argc,char *argv[])
{
	yyin = fopen(argv[1],"r");
	//tex_file = fopen(argv[2],"w+");
	yylex();
}  */   


