
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 95
#define YY_END_OF_BUFFER 96
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[404] =
    {   0,
        1,    1,    0,    0,    0,    0,    0,    0,    0,    0,
       90,   90,   96,   94,    1,    1,   93,   94,   93,   94,
       94,   95,   15,   95,   95,   95,   19,   95,   79,   95,
       95,   25,   95,   95,   95,   90,   90,   90,   90,   95,
       90,   95,    1,    1,   93,    0,   93,    0,    1,   93,
       93,   93,    0,    0,    0,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   93,
        0,    0,    0,    0,    0,   24,    0,    0,    0,   90,
       90,   90,   90,   90,    0,   90,    0,    0,    1,   93,
        0,   93,    0,   93,   93,   92,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   11,   61,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   63,    0,    0,    0,   37,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   59,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   91,   89,    0,   16,   62,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   64,    0,    0,   38,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   60,
        0,    0,    0,    0,   36,    0,    0,   57,    0,   55,

       53,   65,    0,    0,   39,   41,   43,   45,    0,    0,
       20,   49,   51,    0,    0,    0,    0,    0,   87,   83,
        0,   85,   67,   47,    0,    0,    0,    0,    0,    0,
        0,    0,   89,    0,    0,    0,    0,   58,    0,   56,
       54,   66,    0,    0,   40,   42,   44,   46,    0,    0,
       50,   52,    0,    0,    0,    0,    0,   88,   84,    0,
       86,   68,   48,    0,   35,    0,    0,   33,    0,    0,
       17,    0,    0,   20,    0,    0,   73,   75,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    2,
        0,    0,    0,   34,    0,    0,    0,    0,    0,    0,

        0,   74,   76,    0,    0,    7,    0,    0,    0,    0,
       17,    5,    3,    0,    0,   77,    0,    0,    0,    0,
        0,    0,    0,    0,   21,    0,    8,    0,    0,    0,
        0,   30,    6,    4,    0,    0,    0,    0,    0,    0,
        0,    0,   71,    0,   77,    9,    0,   12,    0,   14,
        0,    0,   18,    0,    0,   21,    0,    0,    0,    0,
        0,   72,    0,   80,   10,    0,   31,    0,   26,   69,
       12,   14,    0,   13,   18,    0,    0,    0,   22,    0,
       32,    0,   27,   70,   81,    0,   13,    0,   78,    0,
       23,   22,   82,    0,    0,   78,   23,    0,    0,    0,

       28,   29,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,    1,
        1,    1,    1,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   16,   16,   16,   16,   16,   21,   22,   23,
       24,   25,   26,    8,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   36,   37,   38,   39,   40,   41,
       36,   42,   43,   44,   45,   46,   47,   36,   48,   49,
        1,   50,    1,    8,   51,    1,   52,   53,   54,   55,

       56,   57,   58,   59,   60,   36,   36,   61,   62,   63,
       64,   65,   36,   66,   67,   68,   69,   70,   71,   36,
       72,   73,   74,   75,   74,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[76] =
    {   0,
        1,    2,    2,    3,    2,    4,    5,    6,    6,    2,
        4,    2,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    2,    7,    8,    7,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    7,
        9,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    2,   10
    } ;

static yyconst flex_uint16_t yy_base[420] =
    {   0,
        0,   75,    2,    3,    5,    6,    4,   10,   59,   65,
      150,  225,  966, 1050,  101,    3,  131,  955,  163,  296,
      912, 1050, 1050,    1,    6,    4, 1050,    9, 1050,   19,
      895, 1050,   25,   26,   47,  174,  191,  242,  259,  906,
      272,  909,  206,  240,  287,  913,  364,  906,   12,  367,
      379,  392,   18,   84,  392,  910,  104,   64,  428,   48,
      147,  423,  153,   59,   84,  888,  250,  470,  198,  404,
       84,   85,  104,  120,  148, 1050,   82,  152,  169,  481,
      505,  529,  542,  546,  903,  568,  898,  884,  574,  589,
      903,  601,  896,  604,  616, 1050,  890,  158,  877,  215,

      265,  594,  219,  274,  615,  876,  247,  268,  875,  606,
      657,  285,  895, 1050,  290,  654,  294,  315,  871,  316,
      870,  869,  868,  314,  334,  867,  866,  865,  863,  357,
      337, 1050,  354,  859,  858, 1050,  365,  368,  441,  375,
      857,  853,  371,  852,  851, 1050,  850,  418,  424,  401,
      442,  444,  443,  850,  422, 1050,  869,  449, 1050, 1050,
      491,  444,  474,  847,  469,  846,  842,  841,  511,  479,
      840,  839,  835,  801,  535,  521, 1050,  785,  784, 1050,
      538,  519,  595,  568,  670,  627,  520,  615,  587, 1050,
      584,  569,  661,  577, 1050,  599,  609, 1050,  573, 1050,

     1050, 1050,  616,  622, 1050, 1050, 1050, 1050,  617,  636,
      562, 1050, 1050,  641,  640,  502,  499,  644, 1050, 1050,
      645, 1050, 1050, 1050,  499,  496,  657,  457,  658,  659,
      522,  660,  473,  446,  648,  654,  656, 1050,  445, 1050,
     1050, 1050,  681,  659, 1050, 1050, 1050, 1050,  677,  678,
     1050, 1050,  684,  688,  443,  439,  692, 1050, 1050,  693,
     1050, 1050, 1050,  406, 1050,  673,  680, 1050,  704,  692,
      407,  376,  373,  376,  700,  699, 1050, 1050,  709,  710,
      564,  736,  334,  737,  702,  702,  749,  320,  318, 1050,
      317,  714,  720, 1050,  730,  717,  307,  291,  290,  726,

      725, 1050, 1050,  736,  738, 1050,  731,  730,  732,  744,
      302, 1050, 1050,  279,  744,  299,  277,  773,  774,  775,
      787,  263,  250,  793,  268,  795, 1050,  749,  748,  750,
      747, 1050, 1050, 1050,  244,  772,  242,  235,  768,  233,
      764,  216, 1050,  204,  217, 1050,  810,  216,  811,  215,
      812,  814,  209,  822,  823,  188,  829,  780,  158,  783,
      135, 1050,  129, 1050, 1050,  124, 1050,  801, 1050, 1050,
      134,  133,  831,  127,  124,  833,  835,  841,  105,   64,
     1050,  803, 1050, 1050, 1050,  805,   56,  847,   51,  848,
       50,   49, 1050,  815,  817,   48,   47,  818,   20,    9,

     1050, 1050, 1050,  923,  933,  943,  952,    5,  960,  966,
      975,  983,  991,  999, 1007, 1015, 1023, 1031, 1039
    } ;

static yyconst flex_int16_t yy_def[420] =
    {   0,
      404,  404,  405,  405,  405,  405,  405,  405,  405,  405,
      406,  406,  403,  403,  407,  403,  407,  408,  407,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  409,  409,  409,  409,  403,
      409,  403,  407,  410,  407,  403,  407,  403,  403,  407,
      410,  407,  408,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  407,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  409,
      409,  409,  409,  409,  403,  409,  403,  403,  410,  410,
      403,  410,  403,  407,  410,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  411,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  412,  403,  411,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  413,  414,  403,
      415,  403,  403,  412,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  413,  403,  414,  403,
      416,  415,  403,  403,  403,  403,  417,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  416,  403,  403,  418,  419,  417,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  418,  403,  419,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,    0,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403
    } ;

static yyconst flex_uint16_t yy_nxt[1126] =
    {   0,
       14,   15,   16,   15,   49,   49,   49,   53,  403,   18,
      403,   19,   14,   49,   49,   49,  403,  403,  403,  403,
       19,  403,   20,  403,   14,   21,   23,   23,   29,   27,
       27,   30,   72,  402,   29,   24,   24,   30,   73,   96,
       25,   25,   71,   74,  401,   26,   26,   28,   28,   14,
      397,  396,  392,  397,  396,   77,   30,   72,   75,  387,
       24,   24,   30,   73,   25,   25,   71,   78,   74,   26,
       26,   28,   28,   31,   14,   14,   15,   16,   15,   31,
       77,   79,   75,   32,   18,  123,   19,   14,  393,   32,
      117,   78,   33,  134,  118,   19,   97,   20,   33,   14,

       21,   34,   43,   44,   43,   35,   79,   34,  392,  123,
       46,   35,   47,   98,  148,  117,  153,   33,  134,  118,
      135,   47,  149,   33,   14,   34,   48,  375,  114,   35,
      387,   34,   50,   51,   50,   35,  372,  371,   98,  148,
       46,  153,   47,  115,  135,  116,  149,  150,  385,   14,
       22,   47,   37,  384,   38,   38,   48,   22,   22,  383,
       38,   39,   40,   41,   50,   51,   50,  115,  151,  116,
       41,  150,   46,   22,   47,   42,   81,  132,   82,   82,
      154,  124,  381,   47,   82,   83,  125,   84,   48,  152,
      133,  356,  151,   86,   84,   82,   82,  158,  155,   85,

       22,   82,   83,   87,   84,  154,  124,   43,   44,   43,
      125,   84,  375,  152,  133,   46,   85,   47,  372,  371,
      345,  158,  146,  155,   22,   22,   47,   37,  370,   38,
       38,   48,   22,   22,  147,   38,   39,   40,   41,  160,
      369,   89,   44,   89,   81,   41,   82,   82,   22,   91,
       42,   92,   82,   83,  161,   84,  168,  367,  147,  365,
       92,   81,   84,   82,   82,   93,  364,   85,  362,   82,
       83,  356,   84,  355,   81,   22,   82,   82,  161,   84,
      168,  178,   82,   83,   85,   84,  354,  137,   50,   51,
       50,  162,   84,  138,  139,  163,   46,   85,   47,   22,

       54,  346,  345,  343,  179,  311,  178,   47,  169,  190,
       55,  137,   48,  170,  334,  333,  162,  138,  139,  192,
      163,  191,   56,   57,   58,   59,   60,   61,  179,   62,
       63,  332,   64,  169,  196,   65,   66,  170,   67,   68,
       69,  327,  290,  326,  192,  191,  203,   56,   57,   58,
       59,   60,   61,  197,   62,   63,   64,  320,  196,   65,
       66,  199,   67,   68,   69,   50,   51,   50,   50,   51,
       50,  203,  204,   46,  210,   47,   46,  197,   47,  274,
       95,   51,   95,  209,   47,  199,  211,   47,   91,   48,
       92,  214,   48,   50,   51,   50,  204,  313,  210,   92,

      312,   46,  218,   47,   93,   50,   51,   50,  209,  215,
      311,  211,   47,   46,  221,   47,  214,   48,   99,  100,
      101,  102,  103,  104,   47,  105,  106,  218,  107,   48,
      306,  108,  109,  215,  110,  111,  112,  227,  221,  126,
      127,  128,  129,   99,  100,  101,  102,  103,  104,  225,
      105,  106,  107,  130,  226,  108,  109,  119,  110,  111,
      112,  227,  120,  303,  121,  232,  131,  302,  216,  294,
      290,  122,  228,  229,  225,  230,  233,  234,  130,  226,
      284,  217,  119,   81,  236,   82,   82,  120,  121,  232,
      131,   82,   83,  216,   84,  122,  140,  228,  229,  141,

      230,   84,  234,  142,  143,  217,   85,   81,  236,   82,
       82,  144,  237,  145,  239,   82,   83,  244,   84,  282,
      235,  140,  281,  278,  141,   84,  277,  287,  142,  143,
       85,   81,  287,   82,   82,  144,  237,  145,  239,   82,
       83,  244,   84,  243,   81,  235,   82,   82,   81,   84,
       82,   82,   82,   83,   85,   84,   82,   83,  250,   84,
      254,  249,   84,  260,  253,  274,   84,   85,  243,  318,
       86,   85,   82,   82,  318,   89,   44,   89,   82,   83,
       87,   84,  250,   91,  254,   92,  249,  260,   84,  253,
       95,   51,   95,   85,   92,  257,  287,  268,   91,   93,

       92,  265,   95,   51,   95,   50,   51,   50,  263,   92,
       91,  262,   92,   46,   93,   47,  264,   95,   51,   95,
      257,   92,  255,  164,   47,   91,   93,   92,  165,   48,
      166,  171,  172,  173,  174,  256,   92,  167,  318,  261,
      264,   93,  266,  181,  269,  175,  272,  255,  164,  182,
      183,  259,  267,  165,  166,  193,  193,  193,  176,  256,
      270,  167,  193,  193,  193,  271,  266,  181,  194,  269,
      175,  272,  273,  182,  183,  194,  267,  275,  195,  276,
      279,  280,  176,  184,  270,  195,  185,  283,  285,  271,
      186,  187,  286,  288,  258,  291,  273,  292,  188,  293,

      189,  275,  297,  276,  279,  280,  298,  307,  184,  295,
      308,  185,  283,  285,  299,  186,  187,  286,  288,  291,
      300,  292,  188,  293,  189,  296,  297,  301,  304,  305,
      309,  298,  307,  310,  295,  308,  314,  315,  299,  316,
      317,  319,  321,  322,  300,  323,  319,  321,  328,  296,
      329,  301,  304,  305,  325,  309,  330,  310,  331,  325,
      314,  315,  335,  336,  316,  317,  337,  322,  338,  323,
      339,  340,  341,  328,  342,  329,  344,  361,  348,  350,
      351,  330,  331,  348,  350,  351,  335,  336,  358,  359,
      360,  337,  353,  338,  339,  340,  341,  353,  325,  342,

      357,  344,  361,  325,  363,  357,  366,  368,  252,  251,
      319,  321,  358,  359,  360,  348,  350,  374,  380,  353,
      348,  350,  374,  325,  353,  248,  382,  376,  377,  363,
      366,  368,  376,  377,  379,  386,  374,  394,  389,  379,
      391,  374,  380,  389,  395,  391,  379,  348,  350,  351,
      382,  379,  389,  391,  398,  399,  400,  389,  391,  247,
      386,  353,  394,  246,  245,  242,  241,  325,  395,  357,
      240,  238,  233,  231,  224,  223,  222,  220,  398,  399,
      400,  219,  213,  212,  348,  350,  374,  208,  353,  207,
      206,  205,  202,  201,  200,  198,  376,  377,  113,  180,

      177,  159,  157,  379,   90,  374,   51,  389,  156,  391,
       88,   82,  136,  113,   45,  379,   94,   82,   88,   76,
       70,  389,  391,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   36,   45,   45,   45,   45,   45,   52,   45,
       45,   80,   80,   80,   80,  403,   80,   90,   90,   90,
       90,   90,  403,   90,   90,  289,  289,  289,  289,  289,
      289,  289,  289,  289,  289,  324,  324,  403,  403,  403,
      324,  324,  324,  347,  347,  347,  403,  403,  347,  403,

      347,  349,  349,  403,  403,  403,  349,  403,  349,  352,
      352,  352,  403,  403,  352,  403,  352,  373,  373,  403,
      403,  403,  373,  403,  373,  378,  378,  403,  403,  403,
      378,  403,  378,  388,  388,  403,  403,  403,  388,  403,
      388,  390,  390,  403,  403,  403,  390,  403,  390,   13,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403
    } ;

static yyconst flex_int16_t yy_chk[1126] =
    {   0,
        1,    1,    1,    1,   16,   16,   16,  408,    0,    1,
        0,    1,    1,   49,   49,   49,    0,    0,    0,    0,
        1,   53,    1,    0,    1,    1,    3,    4,    7,    5,
        6,    7,   25,  400,    8,    3,    4,    8,   26,   53,
        3,    4,   24,   28,  399,    3,    4,    5,    6,    1,
      397,  396,  392,  391,  389,   33,    7,   25,   30,  387,
        3,    4,    8,   26,    3,    4,   24,   34,   28,    3,
        4,    5,    6,    9,    1,    2,    2,    2,    2,   10,
       33,   35,   30,    9,    2,   60,    2,    2,  380,   10,
       58,   34,    9,   64,   58,    2,   54,    2,   10,    2,

        2,    9,   15,   15,   15,    9,   35,   10,  379,   60,
       15,   10,   15,   54,   71,   58,   77,    9,   64,   58,
       65,   15,   72,   10,    2,    9,   15,  375,   57,    9,
      374,   10,   17,   17,   17,   10,  372,  371,   54,   71,
       17,   77,   17,   57,   65,   57,   72,   73,  366,    2,
       11,   17,   11,  363,   11,   11,   17,   11,   11,  361,
       11,   11,   11,   11,   19,   19,   19,   57,   74,   57,
       11,   73,   19,   11,   19,   11,   36,   63,   36,   36,
       78,   61,  359,   19,   36,   36,   61,   36,   19,   75,
       63,  356,   74,   37,   36,   37,   37,   98,   79,   36,

       11,   37,   37,   37,   37,   78,   61,   43,   43,   43,
       61,   37,  353,   75,   63,   43,   37,   43,  350,  348,
      345,   98,   69,   79,   11,   12,   43,   12,  344,   12,
       12,   43,   12,   12,   69,   12,   12,   12,   12,  100,
      342,   44,   44,   44,   38,   12,   38,   38,   12,   44,
       12,   44,   38,   38,  100,   38,  103,  340,   69,  338,
       44,   39,   38,   39,   39,   44,  337,   38,  335,   39,
       39,  325,   39,  323,   41,   12,   41,   41,  100,   39,
      103,  107,   41,   41,   39,   41,  322,   67,   45,   45,
       45,  101,   41,   67,   67,  101,   45,   41,   45,   12,

       20,  317,  316,  314,  108,  311,  107,   45,  104,  112,
       20,   67,   45,  104,  299,  298,  101,   67,   67,  115,
      101,  112,   20,   20,   20,   20,   20,   20,  108,   20,
       20,  297,   20,  104,  117,   20,   20,  104,   20,   20,
       20,  291,  289,  288,  115,  112,  124,   20,   20,   20,
       20,   20,   20,  118,   20,   20,   20,  283,  117,   20,
       20,  120,   20,   20,   20,   47,   47,   47,   50,   50,
       50,  124,  125,   47,  131,   47,   50,  118,   50,  274,
       51,   51,   51,  130,   47,  120,  133,   50,   51,   47,
       51,  137,   50,   52,   52,   52,  125,  273,  131,   51,

      272,   52,  140,   52,   51,   70,   70,   70,  130,  138,
      271,  133,   52,   70,  143,   70,  137,   52,   55,   55,
       55,   55,   55,   55,   70,   55,   55,  140,   55,   70,
      264,   55,   55,  138,   55,   55,   55,  150,  143,   62,
       62,   62,   62,   55,   55,   55,   55,   55,   55,  148,
       55,   55,   55,   62,  149,   55,   55,   59,   55,   55,
       55,  150,   59,  256,   59,  155,   62,  255,  139,  239,
      234,   59,  151,  152,  148,  153,  233,  158,   62,  149,
      228,  139,   59,   80,  162,   80,   80,   59,   59,  155,
       62,   80,   80,  139,   80,   59,   68,  151,  152,   68,

      153,   80,  158,   68,   68,  139,   80,   81,  162,   81,
       81,   68,  163,   68,  165,   81,   81,  170,   81,  226,
      161,   68,  225,  217,   68,   81,  216,  231,   68,   68,
       81,   82,  231,   82,   82,   68,  163,   68,  165,   82,
       82,  170,   82,  169,   83,  161,   83,   83,   84,   82,
       84,   84,   83,   83,   82,   83,   84,   84,  176,   84,
      182,  175,   83,  187,  181,  211,   84,   83,  169,  281,
       86,   84,   86,   86,  281,   89,   89,   89,   86,   86,
       86,   86,  176,   89,  182,   89,  175,  187,   86,  181,
       90,   90,   90,   86,   89,  184,  231,  199,   90,   89,

       90,  194,   92,   92,   92,   94,   94,   94,  191,   90,
       92,  189,   92,   94,   90,   94,  192,   95,   95,   95,
      184,   92,  183,  102,   94,   95,   92,   95,  102,   94,
      102,  105,  105,  105,  105,  183,   95,  102,  281,  188,
      192,   95,  196,  110,  203,  105,  209,  183,  102,  110,
      110,  186,  197,  102,  102,  116,  116,  116,  105,  183,
      203,  102,  193,  193,  193,  204,  196,  110,  116,  203,
      105,  209,  210,  110,  110,  193,  197,  214,  116,  215,
      218,  221,  105,  111,  203,  193,  111,  227,  229,  204,
      111,  111,  230,  232,  185,  235,  210,  236,  111,  237,

      111,  214,  244,  215,  218,  221,  249,  266,  111,  243,
      267,  111,  227,  229,  250,  111,  111,  230,  232,  235,
      253,  236,  111,  237,  111,  243,  244,  254,  257,  260,
      269,  249,  266,  270,  243,  267,  275,  276,  250,  279,
      280,  282,  284,  285,  253,  286,  282,  284,  292,  243,
      293,  254,  257,  260,  287,  269,  295,  270,  296,  287,
      275,  276,  300,  301,  279,  280,  304,  285,  305,  286,
      307,  308,  309,  292,  310,  293,  315,  331,  318,  319,
      320,  295,  296,  318,  319,  320,  300,  301,  328,  329,
      330,  304,  321,  305,  307,  308,  309,  321,  324,  310,

      326,  315,  331,  324,  336,  326,  339,  341,  179,  178,
      282,  284,  328,  329,  330,  347,  349,  351,  358,  352,
      347,  349,  351,  287,  352,  174,  360,  354,  355,  336,
      339,  341,  354,  355,  357,  368,  373,  382,  376,  357,
      377,  373,  358,  376,  386,  377,  378,  318,  319,  320,
      360,  378,  388,  390,  394,  395,  398,  388,  390,  173,
      368,  321,  382,  172,  171,  168,  167,  324,  386,  326,
      166,  164,  157,  154,  147,  145,  144,  142,  394,  395,
      398,  141,  135,  134,  347,  349,  351,  129,  352,  128,
      127,  126,  123,  122,  121,  119,  354,  355,  113,  109,

      106,   99,   97,  357,   93,  373,   91,  376,   88,  377,
       87,   85,   66,   56,   48,  378,   46,   42,   40,   31,
       21,  388,  390,  404,  404,  404,  404,  404,  404,  404,
      404,  404,  404,  405,  405,  405,  405,  405,  405,  405,
      405,  405,  405,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  407,  407,  407,  407,  407,   18,  407,
      407,  409,  409,  409,  409,   13,  409,  410,  410,  410,
      410,  410,    0,  410,  410,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  412,  412,    0,    0,    0,
      412,  412,  412,  413,  413,  413,    0,    0,  413,    0,

      413,  414,  414,    0,    0,    0,  414,    0,  414,  415,
      415,  415,    0,    0,  415,    0,  415,  416,  416,    0,
        0,    0,  416,    0,  416,  417,  417,    0,    0,    0,
      417,    0,  417,  418,  418,    0,    0,    0,  418,    0,
      418,  419,  419,    0,    0,    0,  419,    0,  419,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,

      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403,  403,  403,  403,  403,  403,
      403,  403,  403,  403,  403
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "main_lexer.l"
/* Declaration section*/
#line 4 "main_lexer.l"
#include<stdio.h>
#include<string.h>
#include"ast_grammar.tab.h"
#include<bits/stdc++.h>
using namespace std;





#line 864 "lex.yy.c"

#define INITIAL 0
#define href 1
#define sizetag 2
#define table 3
#define src 4
#define comment 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 25 "main_lexer.l"

#line 1089 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 404 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1050 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 26 "main_lexer.l"
;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 32 "main_lexer.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 33 "main_lexer.l"
{	
						//printf("HTML_S\n");
						return HTML_S;
					}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "main_lexer.l"
{	
						//printf("HTML_E\n");
						return HTML_E;
					}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 45 "main_lexer.l"
{	
						//printf("HEAD_S\n");
						return HEAD_S;
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 51 "main_lexer.l"
{	
						//printf("HEAD_E\n");
						return HEAD_E;
					}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "main_lexer.l"
{	
						//printf("BODY_S\n");
						return BODY_S;
					}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 63 "main_lexer.l"
{	
						//printf("BODY_E\n");
						return BODY_E;
					}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "main_lexer.l"
{
						//printf("TITLE_S\n");
						return TITLE_S;
					}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 75 "main_lexer.l"
{
						//printf("TITLE_E\n");
						return TITLE_E;
					}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 81 "main_lexer.l"
{
						//printf("HREF_S\n");
						BEGIN href;
						return HREF_S;
					}
	YY_BREAK

case 12:
YY_RULE_SETUP
#line 89 "main_lexer.l"
{
										char *p = yytext; 
										string str(p);
										
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										int pos = str.find('\'');
										int pos1 = str.find('\"');
									
										if(pos>=0)								
											sscanf(p,"%*[^']'%[^']'",t);
										else 
											sscanf(p, "%*[^\"]\"%[^\"]", t);
										
										strcpy(yylval.s,t);
									
										return HREF_LINK;
									}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "main_lexer.l"
{
										char *p = yytext; 
										string str(p);
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										int pos = str.find('\'');
										int pos1 = str.find('\"');
										if(pos>=0)								
											sscanf(p,"%*[^']'%[^']'",t);
										else 
											sscanf(p, "%*[^\"]\"%[^\"]", t);
										
										strcpy(yylval.s,t);
										return HREF_TITLE;
									}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 125 "main_lexer.l"
{
										char *p = yytext; 
										string str(p);
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);									
										int pos = str.find('\'');
										int pos1 = str.find('\"');
										if(pos>=0)								
											sscanf(p,"%*[^']'%[^']'",t);
										else 
											sscanf(p, "%*[^\"]\"%[^\"]", t);
										
										strcpy(yylval.s,t);
										return HREF_NAME;
									}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 16:
YY_RULE_SETUP
#line 150 "main_lexer.l"
{	
						//printf("HREF_E\n");
						return HREF_E;
					}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 156 "main_lexer.l"
{
						//printf("FONT_S\n\n");

						BEGIN sizetag;
						return FONT_S;
					}
	YY_BREAK

case 18:
YY_RULE_SETUP
#line 165 "main_lexer.l"
{
										char *p = yytext; 
										string str(p);
										int len = strlen( p );
										char t[len+1],t1[len+1];
										yylval.s = (char *)malloc(100);	
										int pos = str.find('\'');
										int pos1 = str.find('\"');
										if(pos>=0)								
											sscanf(p,"%*[^']'%[^']'",t);
										else 
											sscanf(p, "%*[^\"]\"%[^\"]", t);
										
										strcpy(yylval.s,t);
										return FONT_SIZE;
									}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 181 "main_lexer.l"
{
											BEGIN 0;
										
									}
	YY_BREAK

case 20:
YY_RULE_SETUP
#line 187 "main_lexer.l"
{
						//printf("IMG Begin\n");
						BEGIN src;
						return IMG_S;
					}
	YY_BREAK

case 21:
YY_RULE_SETUP
#line 197 "main_lexer.l"
{
									//printf("SRC\n\n");
									char *p = yytext; 
									string str(p);
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									int pos = str.find('\'');
									int pos1 = str.find('\"');
									if(pos>=0)								
										sscanf(p,"%*[^']'%[^']'",t);
									else 
										sscanf(p, "%*[^\"]\"%[^\"]", t);
									
									strcpy(yylval.s,t);
									return IMG_SRC;
								}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 215 "main_lexer.l"
{
									
									char *p = yytext; 
									string str(p);
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									int pos = str.find('\'');
									int pos1 = str.find('\"');
									if(pos>=0)								
										sscanf(p,"%*[^']'%[^']'",t);
									else 
										sscanf(p, "%*[^\"]\"%[^\"]", t);
									
									strcpy(yylval.s,t);
									return IMG_WIDTH;
								}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 234 "main_lexer.l"
{
									
									char *p = yytext; 
									string str(p);
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									int pos = str.find('\'');
									int pos1 = str.find('\"');
									if(pos>=0)								
										sscanf(p,"%*[^']'%[^']'",t);
									else 
										sscanf(p, "%*[^\"]\"%[^\"]", t);
									
									strcpy(yylval.s,t);								
									return IMG_HEIGHT;
								}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 253 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 259 "main_lexer.l"
{	
														
										BEGIN 0;
										return IMG_E;
								}
	YY_BREAK

case 26:
YY_RULE_SETUP
#line 267 "main_lexer.l"
{
						//printf("FIG_S");
						return FIG_S;
					}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 272 "main_lexer.l"
{
						//printf("FIG_E");
						return FIG_E;
					}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 277 "main_lexer.l"
{
						//printf("FIGCAP_S");
						return FIGCAP_S;
					}		
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 282 "main_lexer.l"
{
						//printf("FIGCAP_E");
						return FIGCAP_E;
					}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 287 "main_lexer.l"
{
						//printf("FONT_E\n\n");
						return FONT_E;
					}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 293 "main_lexer.l"
{
						//printf("CENTER_S\n");
						return CENTER_S;
					}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 299 "main_lexer.l"
{
						//printf("CENTER_E\n");
						return CENTER_E;
					}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 305 "main_lexer.l"
{
						//printf("DIV_S\n");
						return DIV_S;
					}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 311 "main_lexer.l"
{
						//printf("DIV_E\n");
						return DIV_E;
					}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 319 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 324 "main_lexer.l"
{
						//printf("BR\n");
						return BR;
					}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 329 "main_lexer.l"
{
						//printf("P_S\n");
						return P_S;
					}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 335 "main_lexer.l"
{
						//printf("P_E\n");
						return P_E;
					}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 341 "main_lexer.l"
{
						//printf("H1_S\n");
						return H1_S;
					}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 347 "main_lexer.l"
{
						//printf("H1_E\n");
						return H1_E;
					}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 353 "main_lexer.l"
{
						//printf("H2_S\n");
						return H2_S;
					}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 359 "main_lexer.l"
{
						//printf("H2_E\n");
						return H2_E;
					}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 365 "main_lexer.l"
{
						//printf("H3_S\n");
						return H3_S;
					}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 370 "main_lexer.l"
{
						//printf("H3_E\n");
						return H3_E;
					}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 375 "main_lexer.l"
{
						//printf("H4_S\n");
						return H4_S;
					}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 381 "main_lexer.l"
{
						//printf("H4_E\n");
						return H4_E;
					}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 387 "main_lexer.l"
{
						//printf("UL_S\n");
						return UL_S;
					}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 393 "main_lexer.l"
{
						//printf("UL_E\n");
						return UL_E;
					}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 398 "main_lexer.l"
{
						//printf("LI_S\n");
						return LI_S;
					}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 404 "main_lexer.l"
{
						//printf("LI_E\n");
						return LI_E;
					}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 409 "main_lexer.l"
{
						//printf("OL_S\n");
						return OL_S;
					}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 415 "main_lexer.l"
{
						//printf("OL_E\n");
						return OL_E;
					}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 420 "main_lexer.l"
{
						//printf("DT_S\n");
						return DT_S;
					}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 426 "main_lexer.l"
{
						//printf("DT_E\n");
						return DT_E;
					}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 431 "main_lexer.l"
{
						//printf("DL_S\n");
						return DL_S;
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 437 "main_lexer.l"
{
						//printf("DL_E\n");
						return DL_E;
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 442 "main_lexer.l"
{
						//printf("DD_S\n");
						return DD_S;
					}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 448 "main_lexer.l"
{
						//printf("DD_E\n");
						return DD_E;
					}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 454 "main_lexer.l"
{
						//printf("U_S\n");
						return U_S;
					}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 459 "main_lexer.l"
{
						//printf("U_E\n");
						return U_E;
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 464 "main_lexer.l"
{
						//printf("B_S\n");
						return B_S;
					}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 469 "main_lexer.l"
{
						//printf("B_E\n");
						return B_E;
					}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 474 "main_lexer.l"
{
						//printf("I_S\n");
						return I_S;
					}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 479 "main_lexer.l"
{
						//printf("I_E\n");
						return I_E;
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 484 "main_lexer.l"
{
						//printf("EM_S\n");
						return EM_S;
					}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 489 "main_lexer.l"
{
						//printf("EM_E\n");
						return EM_E;
					}					
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 494 "main_lexer.l"
{
						//printf("TT_S\n");
						return TT_S;
					}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 499 "main_lexer.l"
{
						//printf("TT_E\n");
						return TT_E;
					}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 505 "main_lexer.l"
{
						//printf("STRONG_S\n");
						return STRONG_S;
					}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 510 "main_lexer.l"
{
						//printf("STRONG_E\n");
						return STRONG_E;
					}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 516 "main_lexer.l"
{
						//printf("SMALL_S\n");
						return SMALL_S;
					}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 521 "main_lexer.l"
{
						//printf("SMALL_E\n");
						return SMALL_E;
					}			
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 528 "main_lexer.l"
{
						//printf("SUB_S\n");
						return SUB_S;
					}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 534 "main_lexer.l"
{
						//printf("SUB_E\n");
						return SUB_E;
					}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 539 "main_lexer.l"
{
						//printf("SUP_S\n");
						return SUP_S;
					}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 545 "main_lexer.l"
{
						//printf("SUP_E\n");
						return SUP_E;
					}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 550 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN table;
						return TABLE_S;
					}
	YY_BREAK

case 78:
YY_RULE_SETUP
#line 558 "main_lexer.l"
{
									//printf("BORDER i\n\n");
									char *p = yytext; 
									string str(p);
									int len = strlen( p );
									char t[len+1],t1[len+1];
									yylval.s = (char *)malloc(100);									
									int pos = str.find('\'');
									int pos1 = str.find('\"');
									if(pos>=0)								
										sscanf(p,"%*[^']'%[^']'",t);
									else 
										sscanf(p, "%*[^\"]\"%[^\"]", t);
									
									strcpy(yylval.s,t);		
									return TABLE_BORDER;
								}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 576 "main_lexer.l"
{
										BEGIN 0;
								}	
	YY_BREAK

case 80:
YY_RULE_SETUP
#line 584 "main_lexer.l"
{
						//printf("TABLE_E\n");
						return TABLE_E;
					}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 590 "main_lexer.l"
{
						//printf("CAPTION_S\n");
						return CAPTION_S;
					}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 596 "main_lexer.l"
{
						//printf("CAPTION_E\n");
						return CAPTION_E;
					}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 602 "main_lexer.l"
{
						//printf("TH_S\n");
						return TH_S;
					}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 608 "main_lexer.l"
{
						//printf("TH_E\n");
						return TH_E;
					}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 614 "main_lexer.l"
{
						//printf("TR_S\n");
						return TR_S;
					}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 620 "main_lexer.l"
{
						//printf("TR_E\n");
						return TR_E;
					}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 626 "main_lexer.l"
{
						//printf("TD_S\n");
						return TD_S;
					}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 632 "main_lexer.l"
{
						//printf("TD_E\n");
						return TD_E;
					}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 638 "main_lexer.l"
{
						//printf("TABLE_S\n");
						BEGIN comment;
						//return TABLE_S;
					}
	YY_BREAK

case 90:
/* rule 90 can match eol */
YY_RULE_SETUP
#line 646 "main_lexer.l"
{
										
										yylval.s = (char *)malloc(100);	
										yylval.s = yytext;
										return COMMENT;
										
									}
	YY_BREAK
case 91:
/* rule 91 can match eol */
YY_RULE_SETUP
#line 653 "main_lexer.l"
{
										BEGIN 0;
									}
	YY_BREAK

case 92:
YY_RULE_SETUP
#line 661 "main_lexer.l"
{	
						
						yylval.s = strdup(yytext);
						return GREEK;
					}
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 667 "main_lexer.l"
{
						
						
						yylval.s = strdup(yytext);
						string str(yylval.s);
						char find_vec[] = {'_','#','%','$','&','{','}','~','^'};
						vector<string> replace_vec = {"\\_","\\#","\\%","\\$","\\&","\\{","\\}","\\sim","\\hat{}"};
						int pos;
						string str1(str);
						string str2("");
						for(int i=0;i<replace_vec.size();i++)
						{
							for (int j=0;j<str1.length();j++)
							{
								if(str1[j]==find_vec[i])
									str2+=replace_vec[i];
								else
									str2+=str1[j];
							}
							str1=str2;
							str2="";
									
	   					}
	   					yylval.s = strdup(str1.c_str());

						return DATA;
					}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 701 "main_lexer.l"
{ 
						yylval.s=strdup(yytext);
						return DATA;
					}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 707 "main_lexer.l"
ECHO;
	YY_BREAK
#line 2050 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(href):
case YY_STATE_EOF(sizetag):
case YY_STATE_EOF(table):
case YY_STATE_EOF(src):
case YY_STATE_EOF(comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 404 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 404 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 403);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 707 "main_lexer.l"


  
int yywrap()
{
	return 1;	
} 
 


